// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.23.0-devel
// 	protoc        v3.19.1
// source: CommonMsg.proto

package netproto

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type AnnRange int32

const (
	AnnRange_AnnRange_All  AnnRange = 0
	AnnRange_AnnRange_Hall AnnRange = 1
	AnnRange_AnnRange_Game AnnRange = 2
)

// Enum value maps for AnnRange.
var (
	AnnRange_name = map[int32]string{
		0: "AnnRange_All",
		1: "AnnRange_Hall",
		2: "AnnRange_Game",
	}
	AnnRange_value = map[string]int32{
		"AnnRange_All":  0,
		"AnnRange_Hall": 1,
		"AnnRange_Game": 2,
	}
)

func (x AnnRange) Enum() *AnnRange {
	p := new(AnnRange)
	*p = x
	return p
}

func (x AnnRange) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AnnRange) Descriptor() protoreflect.EnumDescriptor {
	return file_CommonMsg_proto_enumTypes[0].Descriptor()
}

func (AnnRange) Type() protoreflect.EnumType {
	return &file_CommonMsg_proto_enumTypes[0]
}

func (x AnnRange) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *AnnRange) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = AnnRange(num)
	return nil
}

// Deprecated: Use AnnRange.Descriptor instead.
func (AnnRange) EnumDescriptor() ([]byte, []int) {
	return file_CommonMsg_proto_rawDescGZIP(), []int{0}
}

type AnnPriority int32

const (
	AnnPriority_AnnPriority_Low    AnnPriority = 0
	AnnPriority_AnnPriority_Normal AnnPriority = 1
	AnnPriority_AnnPriority_Hight  AnnPriority = 2
)

// Enum value maps for AnnPriority.
var (
	AnnPriority_name = map[int32]string{
		0: "AnnPriority_Low",
		1: "AnnPriority_Normal",
		2: "AnnPriority_Hight",
	}
	AnnPriority_value = map[string]int32{
		"AnnPriority_Low":    0,
		"AnnPriority_Normal": 1,
		"AnnPriority_Hight":  2,
	}
)

func (x AnnPriority) Enum() *AnnPriority {
	p := new(AnnPriority)
	*p = x
	return p
}

func (x AnnPriority) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AnnPriority) Descriptor() protoreflect.EnumDescriptor {
	return file_CommonMsg_proto_enumTypes[1].Descriptor()
}

func (AnnPriority) Type() protoreflect.EnumType {
	return &file_CommonMsg_proto_enumTypes[1]
}

func (x AnnPriority) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *AnnPriority) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = AnnPriority(num)
	return nil
}

// Deprecated: Use AnnPriority.Descriptor instead.
func (AnnPriority) EnumDescriptor() ([]byte, []int) {
	return file_CommonMsg_proto_rawDescGZIP(), []int{1}
}

// 通用道具ID
type ItemID int32

const (
	ItemID_None             ItemID = 0
	ItemID_USDT             ItemID = 1
	ItemID_DailySignLottery ItemID = 10 // 每日登入的抽獎
)

// Enum value maps for ItemID.
var (
	ItemID_name = map[int32]string{
		0:  "None",
		1:  "USDT",
		10: "DailySignLottery",
	}
	ItemID_value = map[string]int32{
		"None":             0,
		"USDT":             1,
		"DailySignLottery": 10,
	}
)

func (x ItemID) Enum() *ItemID {
	p := new(ItemID)
	*p = x
	return p
}

func (x ItemID) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ItemID) Descriptor() protoreflect.EnumDescriptor {
	return file_CommonMsg_proto_enumTypes[2].Descriptor()
}

func (ItemID) Type() protoreflect.EnumType {
	return &file_CommonMsg_proto_enumTypes[2]
}

func (x ItemID) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *ItemID) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = ItemID(num)
	return nil
}

// Deprecated: Use ItemID.Descriptor instead.
func (ItemID) EnumDescriptor() ([]byte, []int) {
	return file_CommonMsg_proto_rawDescGZIP(), []int{2}
}

type RetMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code       *int32  `protobuf:"varint,1,req,name=Code" json:"Code,omitempty"`
	Message    *string `protobuf:"bytes,2,req,name=Message" json:"Message,omitempty"`
	ParamLG    *string `protobuf:"bytes,3,opt,name=ParamLG" json:"ParamLG,omitempty"` //錯誤附帶參數， 多參數以|分割（兼容國際化版本）
	InviteCode *string `protobuf:"bytes,4,opt,name=InviteCode" json:"InviteCode,omitempty"`
}

func (x *RetMessage) Reset() {
	*x = RetMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_CommonMsg_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RetMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetMessage) ProtoMessage() {}

func (x *RetMessage) ProtoReflect() protoreflect.Message {
	mi := &file_CommonMsg_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetMessage.ProtoReflect.Descriptor instead.
func (*RetMessage) Descriptor() ([]byte, []int) {
	return file_CommonMsg_proto_rawDescGZIP(), []int{0}
}

func (x *RetMessage) GetCode() int32 {
	if x != nil && x.Code != nil {
		return *x.Code
	}
	return 0
}

func (x *RetMessage) GetMessage() string {
	if x != nil && x.Message != nil {
		return *x.Message
	}
	return ""
}

func (x *RetMessage) GetParamLG() string {
	if x != nil && x.ParamLG != nil {
		return *x.ParamLG
	}
	return ""
}

func (x *RetMessage) GetInviteCode() string {
	if x != nil && x.InviteCode != nil {
		return *x.InviteCode
	}
	return ""
}

type RPCInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ConnID        *string `protobuf:"bytes,1,req,name=ConnID" json:"ConnID,omitempty"`
	QueueID       *int32  `protobuf:"varint,2,req,name=QueueID" json:"QueueID,omitempty"`
	IPAddress     *string `protobuf:"bytes,3,req,name=IPAddress" json:"IPAddress,omitempty"`
	UserID        *int32  `protobuf:"varint,4,opt,name=UserID" json:"UserID,omitempty"`
	Cer           *string `protobuf:"bytes,5,opt,name=Cer" json:"Cer,omitempty"`
	RouteServerID *int32  `protobuf:"varint,6,req,name=RouteServerID" json:"RouteServerID,omitempty"`
	ExtendInfo    *string `protobuf:"bytes,7,opt,name=ExtendInfo" json:"ExtendInfo,omitempty"`
}

func (x *RPCInfo) Reset() {
	*x = RPCInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_CommonMsg_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RPCInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RPCInfo) ProtoMessage() {}

func (x *RPCInfo) ProtoReflect() protoreflect.Message {
	mi := &file_CommonMsg_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RPCInfo.ProtoReflect.Descriptor instead.
func (*RPCInfo) Descriptor() ([]byte, []int) {
	return file_CommonMsg_proto_rawDescGZIP(), []int{1}
}

func (x *RPCInfo) GetConnID() string {
	if x != nil && x.ConnID != nil {
		return *x.ConnID
	}
	return ""
}

func (x *RPCInfo) GetQueueID() int32 {
	if x != nil && x.QueueID != nil {
		return *x.QueueID
	}
	return 0
}

func (x *RPCInfo) GetIPAddress() string {
	if x != nil && x.IPAddress != nil {
		return *x.IPAddress
	}
	return ""
}

func (x *RPCInfo) GetUserID() int32 {
	if x != nil && x.UserID != nil {
		return *x.UserID
	}
	return 0
}

func (x *RPCInfo) GetCer() string {
	if x != nil && x.Cer != nil {
		return *x.Cer
	}
	return ""
}

func (x *RPCInfo) GetRouteServerID() int32 {
	if x != nil && x.RouteServerID != nil {
		return *x.RouteServerID
	}
	return 0
}

func (x *RPCInfo) GetExtendInfo() string {
	if x != nil && x.ExtendInfo != nil {
		return *x.ExtendInfo
	}
	return ""
}

type TipMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message *string `protobuf:"bytes,1,req,name=Message" json:"Message,omitempty"`
	MsgType *int32  `protobuf:"varint,2,req,name=MsgType" json:"MsgType,omitempty"`
	Param   *int32  `protobuf:"varint,3,opt,name=Param" json:"Param,omitempty"`
	CodeLG  *int32  `protobuf:"varint,4,opt,name=CodeLG" json:"CodeLG,omitempty"`  //錯誤id		（兼容國際化版本）
	ParamLG *string `protobuf:"bytes,5,opt,name=ParamLG" json:"ParamLG,omitempty"` //錯誤附帶參數， 多參數以|分割（兼容國際化版本）
}

func (x *TipMessage) Reset() {
	*x = TipMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_CommonMsg_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TipMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TipMessage) ProtoMessage() {}

func (x *TipMessage) ProtoReflect() protoreflect.Message {
	mi := &file_CommonMsg_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TipMessage.ProtoReflect.Descriptor instead.
func (*TipMessage) Descriptor() ([]byte, []int) {
	return file_CommonMsg_proto_rawDescGZIP(), []int{2}
}

func (x *TipMessage) GetMessage() string {
	if x != nil && x.Message != nil {
		return *x.Message
	}
	return ""
}

func (x *TipMessage) GetMsgType() int32 {
	if x != nil && x.MsgType != nil {
		return *x.MsgType
	}
	return 0
}

func (x *TipMessage) GetParam() int32 {
	if x != nil && x.Param != nil {
		return *x.Param
	}
	return 0
}

func (x *TipMessage) GetCodeLG() int32 {
	if x != nil && x.CodeLG != nil {
		return *x.CodeLG
	}
	return 0
}

func (x *TipMessage) GetParamLG() string {
	if x != nil && x.ParamLG != nil {
		return *x.ParamLG
	}
	return ""
}

type HeartBeatConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BeatInterval     *int32 `protobuf:"varint,1,req,name=BeatInterval" json:"BeatInterval,omitempty"`
	ConnLoseTimeSpan *int32 `protobuf:"varint,2,req,name=ConnLoseTimeSpan" json:"ConnLoseTimeSpan,omitempty"`
}

func (x *HeartBeatConfig) Reset() {
	*x = HeartBeatConfig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_CommonMsg_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HeartBeatConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartBeatConfig) ProtoMessage() {}

func (x *HeartBeatConfig) ProtoReflect() protoreflect.Message {
	mi := &file_CommonMsg_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartBeatConfig.ProtoReflect.Descriptor instead.
func (*HeartBeatConfig) Descriptor() ([]byte, []int) {
	return file_CommonMsg_proto_rawDescGZIP(), []int{3}
}

func (x *HeartBeatConfig) GetBeatInterval() int32 {
	if x != nil && x.BeatInterval != nil {
		return *x.BeatInterval
	}
	return 0
}

func (x *HeartBeatConfig) GetConnLoseTimeSpan() int32 {
	if x != nil && x.ConnLoseTimeSpan != nil {
		return *x.ConnLoseTimeSpan
	}
	return 0
}

type IPReport struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IPAddress *string `protobuf:"bytes,1,req,name=IPAddress" json:"IPAddress,omitempty"`
}

func (x *IPReport) Reset() {
	*x = IPReport{}
	if protoimpl.UnsafeEnabled {
		mi := &file_CommonMsg_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IPReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IPReport) ProtoMessage() {}

func (x *IPReport) ProtoReflect() protoreflect.Message {
	mi := &file_CommonMsg_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IPReport.ProtoReflect.Descriptor instead.
func (*IPReport) Descriptor() ([]byte, []int) {
	return file_CommonMsg_proto_rawDescGZIP(), []int{4}
}

func (x *IPReport) GetIPAddress() string {
	if x != nil && x.IPAddress != nil {
		return *x.IPAddress
	}
	return ""
}

type CheatCodeMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type     *int32   `protobuf:"varint,1,req,name=Type" json:"Type,omitempty"`
	ParamStr []string `protobuf:"bytes,2,rep,name=ParamStr" json:"ParamStr,omitempty"`
	ParamInt []int32  `protobuf:"varint,3,rep,name=ParamInt" json:"ParamInt,omitempty"`
}

func (x *CheatCodeMsg) Reset() {
	*x = CheatCodeMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_CommonMsg_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheatCodeMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheatCodeMsg) ProtoMessage() {}

func (x *CheatCodeMsg) ProtoReflect() protoreflect.Message {
	mi := &file_CommonMsg_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheatCodeMsg.ProtoReflect.Descriptor instead.
func (*CheatCodeMsg) Descriptor() ([]byte, []int) {
	return file_CommonMsg_proto_rawDescGZIP(), []int{5}
}

func (x *CheatCodeMsg) GetType() int32 {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return 0
}

func (x *CheatCodeMsg) GetParamStr() []string {
	if x != nil {
		return x.ParamStr
	}
	return nil
}

func (x *CheatCodeMsg) GetParamInt() []int32 {
	if x != nil {
		return x.ParamInt
	}
	return nil
}

// 通用道具結構
type Item struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ItemID *int32 `protobuf:"varint,1,req,name=ItemID" json:"ItemID,omitempty"`
	Count  *int32 `protobuf:"varint,2,req,name=Count" json:"Count,omitempty"`
}

func (x *Item) Reset() {
	*x = Item{}
	if protoimpl.UnsafeEnabled {
		mi := &file_CommonMsg_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Item) ProtoMessage() {}

func (x *Item) ProtoReflect() protoreflect.Message {
	mi := &file_CommonMsg_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Item.ProtoReflect.Descriptor instead.
func (*Item) Descriptor() ([]byte, []int) {
	return file_CommonMsg_proto_rawDescGZIP(), []int{6}
}

func (x *Item) GetItemID() int32 {
	if x != nil && x.ItemID != nil {
		return *x.ItemID
	}
	return 0
}

func (x *Item) GetCount() int32 {
	if x != nil && x.Count != nil {
		return *x.Count
	}
	return 0
}

var File_CommonMsg_proto protoreflect.FileDescriptor

var file_CommonMsg_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x4d, 0x73, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x08, 0x6e, 0x65, 0x74, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x74, 0x0a, 0x0a, 0x52,
	0x65, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x43, 0x6f, 0x64,
	0x65, 0x18, 0x01, 0x20, 0x02, 0x28, 0x05, 0x52, 0x04, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a,
	0x07, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x02, 0x28, 0x09, 0x52, 0x07,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x50, 0x61, 0x72, 0x61, 0x6d,
	0x4c, 0x47, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x4c,
	0x47, 0x12, 0x1e, 0x0a, 0x0a, 0x49, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x43, 0x6f, 0x64, 0x65, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x49, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x43, 0x6f, 0x64,
	0x65, 0x22, 0xc9, 0x01, 0x0a, 0x07, 0x52, 0x50, 0x43, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x16, 0x0a,
	0x06, 0x43, 0x6f, 0x6e, 0x6e, 0x49, 0x44, 0x18, 0x01, 0x20, 0x02, 0x28, 0x09, 0x52, 0x06, 0x43,
	0x6f, 0x6e, 0x6e, 0x49, 0x44, 0x12, 0x18, 0x0a, 0x07, 0x51, 0x75, 0x65, 0x75, 0x65, 0x49, 0x44,
	0x18, 0x02, 0x20, 0x02, 0x28, 0x05, 0x52, 0x07, 0x51, 0x75, 0x65, 0x75, 0x65, 0x49, 0x44, 0x12,
	0x1c, 0x0a, 0x09, 0x49, 0x50, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x03, 0x20, 0x02,
	0x28, 0x09, 0x52, 0x09, 0x49, 0x50, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x16, 0x0a,
	0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x55,
	0x73, 0x65, 0x72, 0x49, 0x44, 0x12, 0x10, 0x0a, 0x03, 0x43, 0x65, 0x72, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x43, 0x65, 0x72, 0x12, 0x24, 0x0a, 0x0d, 0x52, 0x6f, 0x75, 0x74, 0x65,
	0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x49, 0x44, 0x18, 0x06, 0x20, 0x02, 0x28, 0x05, 0x52, 0x0d,
	0x52, 0x6f, 0x75, 0x74, 0x65, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x49, 0x44, 0x12, 0x1e, 0x0a,
	0x0a, 0x45, 0x78, 0x74, 0x65, 0x6e, 0x64, 0x49, 0x6e, 0x66, 0x6f, 0x18, 0x07, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0a, 0x45, 0x78, 0x74, 0x65, 0x6e, 0x64, 0x49, 0x6e, 0x66, 0x6f, 0x22, 0x88, 0x01,
	0x0a, 0x0a, 0x54, 0x69, 0x70, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x18, 0x0a, 0x07,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x02, 0x28, 0x09, 0x52, 0x07, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x4d, 0x73, 0x67, 0x54, 0x79, 0x70,
	0x65, 0x18, 0x02, 0x20, 0x02, 0x28, 0x05, 0x52, 0x07, 0x4d, 0x73, 0x67, 0x54, 0x79, 0x70, 0x65,
	0x12, 0x14, 0x0a, 0x05, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x05, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x12, 0x16, 0x0a, 0x06, 0x43, 0x6f, 0x64, 0x65, 0x4c, 0x47,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x43, 0x6f, 0x64, 0x65, 0x4c, 0x47, 0x12, 0x18,
	0x0a, 0x07, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x4c, 0x47, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x4c, 0x47, 0x22, 0x61, 0x0a, 0x0f, 0x48, 0x65, 0x61, 0x72,
	0x74, 0x42, 0x65, 0x61, 0x74, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x22, 0x0a, 0x0c, 0x42,
	0x65, 0x61, 0x74, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x76, 0x61, 0x6c, 0x18, 0x01, 0x20, 0x02, 0x28,
	0x05, 0x52, 0x0c, 0x42, 0x65, 0x61, 0x74, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x76, 0x61, 0x6c, 0x12,
	0x2a, 0x0a, 0x10, 0x43, 0x6f, 0x6e, 0x6e, 0x4c, 0x6f, 0x73, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x53,
	0x70, 0x61, 0x6e, 0x18, 0x02, 0x20, 0x02, 0x28, 0x05, 0x52, 0x10, 0x43, 0x6f, 0x6e, 0x6e, 0x4c,
	0x6f, 0x73, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x53, 0x70, 0x61, 0x6e, 0x22, 0x28, 0x0a, 0x08, 0x49,
	0x50, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x49, 0x50, 0x41, 0x64, 0x64,
	0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x02, 0x28, 0x09, 0x52, 0x09, 0x49, 0x50, 0x41, 0x64,
	0x64, 0x72, 0x65, 0x73, 0x73, 0x22, 0x5a, 0x0a, 0x0c, 0x43, 0x68, 0x65, 0x61, 0x74, 0x43, 0x6f,
	0x64, 0x65, 0x4d, 0x73, 0x67, 0x12, 0x12, 0x0a, 0x04, 0x54, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20,
	0x02, 0x28, 0x05, 0x52, 0x04, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x50, 0x61, 0x72,
	0x61, 0x6d, 0x53, 0x74, 0x72, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x08, 0x50, 0x61, 0x72,
	0x61, 0x6d, 0x53, 0x74, 0x72, 0x12, 0x1a, 0x0a, 0x08, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x49, 0x6e,
	0x74, 0x18, 0x03, 0x20, 0x03, 0x28, 0x05, 0x52, 0x08, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x49, 0x6e,
	0x74, 0x22, 0x34, 0x0a, 0x04, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x16, 0x0a, 0x06, 0x49, 0x74, 0x65,
	0x6d, 0x49, 0x44, 0x18, 0x01, 0x20, 0x02, 0x28, 0x05, 0x52, 0x06, 0x49, 0x74, 0x65, 0x6d, 0x49,
	0x44, 0x12, 0x14, 0x0a, 0x05, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x02, 0x28, 0x05,
	0x52, 0x05, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x2a, 0x42, 0x0a, 0x08, 0x41, 0x6e, 0x6e, 0x52, 0x61,
	0x6e, 0x67, 0x65, 0x12, 0x10, 0x0a, 0x0c, 0x41, 0x6e, 0x6e, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x5f,
	0x41, 0x6c, 0x6c, 0x10, 0x00, 0x12, 0x11, 0x0a, 0x0d, 0x41, 0x6e, 0x6e, 0x52, 0x61, 0x6e, 0x67,
	0x65, 0x5f, 0x48, 0x61, 0x6c, 0x6c, 0x10, 0x01, 0x12, 0x11, 0x0a, 0x0d, 0x41, 0x6e, 0x6e, 0x52,
	0x61, 0x6e, 0x67, 0x65, 0x5f, 0x47, 0x61, 0x6d, 0x65, 0x10, 0x02, 0x2a, 0x51, 0x0a, 0x0b, 0x41,
	0x6e, 0x6e, 0x50, 0x72, 0x69, 0x6f, 0x72, 0x69, 0x74, 0x79, 0x12, 0x13, 0x0a, 0x0f, 0x41, 0x6e,
	0x6e, 0x50, 0x72, 0x69, 0x6f, 0x72, 0x69, 0x74, 0x79, 0x5f, 0x4c, 0x6f, 0x77, 0x10, 0x00, 0x12,
	0x16, 0x0a, 0x12, 0x41, 0x6e, 0x6e, 0x50, 0x72, 0x69, 0x6f, 0x72, 0x69, 0x74, 0x79, 0x5f, 0x4e,
	0x6f, 0x72, 0x6d, 0x61, 0x6c, 0x10, 0x01, 0x12, 0x15, 0x0a, 0x11, 0x41, 0x6e, 0x6e, 0x50, 0x72,
	0x69, 0x6f, 0x72, 0x69, 0x74, 0x79, 0x5f, 0x48, 0x69, 0x67, 0x68, 0x74, 0x10, 0x02, 0x2a, 0x32,
	0x0a, 0x06, 0x49, 0x74, 0x65, 0x6d, 0x49, 0x44, 0x12, 0x08, 0x0a, 0x04, 0x4e, 0x6f, 0x6e, 0x65,
	0x10, 0x00, 0x12, 0x08, 0x0a, 0x04, 0x55, 0x53, 0x44, 0x54, 0x10, 0x01, 0x12, 0x14, 0x0a, 0x10,
	0x44, 0x61, 0x69, 0x6c, 0x79, 0x53, 0x69, 0x67, 0x6e, 0x4c, 0x6f, 0x74, 0x74, 0x65, 0x72, 0x79,
	0x10, 0x0a, 0x42, 0x0c, 0x5a, 0x0a, 0x2e, 0x2f, 0x6e, 0x65, 0x74, 0x70, 0x72, 0x6f, 0x74, 0x6f,
}

var (
	file_CommonMsg_proto_rawDescOnce sync.Once
	file_CommonMsg_proto_rawDescData = file_CommonMsg_proto_rawDesc
)

func file_CommonMsg_proto_rawDescGZIP() []byte {
	file_CommonMsg_proto_rawDescOnce.Do(func() {
		file_CommonMsg_proto_rawDescData = protoimpl.X.CompressGZIP(file_CommonMsg_proto_rawDescData)
	})
	return file_CommonMsg_proto_rawDescData
}

var file_CommonMsg_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_CommonMsg_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_CommonMsg_proto_goTypes = []interface{}{
	(AnnRange)(0),           // 0: netproto.AnnRange
	(AnnPriority)(0),        // 1: netproto.AnnPriority
	(ItemID)(0),             // 2: netproto.ItemID
	(*RetMessage)(nil),      // 3: netproto.RetMessage
	(*RPCInfo)(nil),         // 4: netproto.RPCInfo
	(*TipMessage)(nil),      // 5: netproto.TipMessage
	(*HeartBeatConfig)(nil), // 6: netproto.HeartBeatConfig
	(*IPReport)(nil),        // 7: netproto.IPReport
	(*CheatCodeMsg)(nil),    // 8: netproto.CheatCodeMsg
	(*Item)(nil),            // 9: netproto.Item
}
var file_CommonMsg_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_CommonMsg_proto_init() }
func file_CommonMsg_proto_init() {
	if File_CommonMsg_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_CommonMsg_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RetMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_CommonMsg_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RPCInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_CommonMsg_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TipMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_CommonMsg_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HeartBeatConfig); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_CommonMsg_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IPReport); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_CommonMsg_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CheatCodeMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_CommonMsg_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Item); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_CommonMsg_proto_rawDesc,
			NumEnums:      3,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_CommonMsg_proto_goTypes,
		DependencyIndexes: file_CommonMsg_proto_depIdxs,
		EnumInfos:         file_CommonMsg_proto_enumTypes,
		MessageInfos:      file_CommonMsg_proto_msgTypes,
	}.Build()
	File_CommonMsg_proto = out.File
	file_CommonMsg_proto_rawDesc = nil
	file_CommonMsg_proto_goTypes = nil
	file_CommonMsg_proto_depIdxs = nil
}
