// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.23.0-devel
// 	protoc        v3.19.1
// source: GameMsg_BJL.proto

package netproto

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

//下注設定
type BJL_Setting struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BetCount      []int32 `protobuf:"varint,1,rep,name=BetCount" json:"BetCount,omitempty"`           //一次下注的數量
	BetMoney      *int32  `protobuf:"varint,2,req,name=BetMoney" json:"BetMoney,omitempty"`           //一次下注的錢
	BetMoneyLimit *int64  `protobuf:"varint,3,req,name=BetMoneyLimit" json:"BetMoneyLimit,omitempty"` //下注上限
	ZhuangLimit   *int64  `protobuf:"varint,4,req,name=ZhuangLimit" json:"ZhuangLimit,omitempty"`     //上莊錢限製
	MaxZhuang     *int32  `protobuf:"varint,5,req,name=MaxZhuang" json:"MaxZhuang,omitempty"`         //當莊局數
	CanBetLimit   *int64  `protobuf:"varint,6,opt,name=CanBetLimit" json:"CanBetLimit,omitempty"`     //可以押注需要的金幣下限
	BetTypeLimit  []int64 `protobuf:"varint,7,rep,name=BetTypeLimit" json:"BetTypeLimit,omitempty"`   //方位下注最大限製(0表示不限製)
	IsCanBet      *int32  `protobuf:"varint,8,opt,name=IsCanBet" json:"IsCanBet,omitempty"`           //是否可以下注（1:未超過限製可以下注，0:不允許下注）
}

func (x *BJL_Setting) Reset() {
	*x = BJL_Setting{}
	if protoimpl.UnsafeEnabled {
		mi := &file_GameMsg_BJL_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BJL_Setting) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BJL_Setting) ProtoMessage() {}

func (x *BJL_Setting) ProtoReflect() protoreflect.Message {
	mi := &file_GameMsg_BJL_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BJL_Setting.ProtoReflect.Descriptor instead.
func (*BJL_Setting) Descriptor() ([]byte, []int) {
	return file_GameMsg_BJL_proto_rawDescGZIP(), []int{0}
}

func (x *BJL_Setting) GetBetCount() []int32 {
	if x != nil {
		return x.BetCount
	}
	return nil
}

func (x *BJL_Setting) GetBetMoney() int32 {
	if x != nil && x.BetMoney != nil {
		return *x.BetMoney
	}
	return 0
}

func (x *BJL_Setting) GetBetMoneyLimit() int64 {
	if x != nil && x.BetMoneyLimit != nil {
		return *x.BetMoneyLimit
	}
	return 0
}

func (x *BJL_Setting) GetZhuangLimit() int64 {
	if x != nil && x.ZhuangLimit != nil {
		return *x.ZhuangLimit
	}
	return 0
}

func (x *BJL_Setting) GetMaxZhuang() int32 {
	if x != nil && x.MaxZhuang != nil {
		return *x.MaxZhuang
	}
	return 0
}

func (x *BJL_Setting) GetCanBetLimit() int64 {
	if x != nil && x.CanBetLimit != nil {
		return *x.CanBetLimit
	}
	return 0
}

func (x *BJL_Setting) GetBetTypeLimit() []int64 {
	if x != nil {
		return x.BetTypeLimit
	}
	return nil
}

func (x *BJL_Setting) GetIsCanBet() int32 {
	if x != nil && x.IsCanBet != nil {
		return *x.IsCanBet
	}
	return 0
}

//狀態消息
type BJL_Sate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	State *int32 `protobuf:"varint,1,req,name=State" json:"State,omitempty"` //狀態
	Time  *int32 `protobuf:"varint,2,req,name=Time" json:"Time,omitempty"`   //此狀態的剩餘時間
}

func (x *BJL_Sate) Reset() {
	*x = BJL_Sate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_GameMsg_BJL_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BJL_Sate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BJL_Sate) ProtoMessage() {}

func (x *BJL_Sate) ProtoReflect() protoreflect.Message {
	mi := &file_GameMsg_BJL_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BJL_Sate.ProtoReflect.Descriptor instead.
func (*BJL_Sate) Descriptor() ([]byte, []int) {
	return file_GameMsg_BJL_proto_rawDescGZIP(), []int{1}
}

func (x *BJL_Sate) GetState() int32 {
	if x != nil && x.State != nil {
		return *x.State
	}
	return 0
}

func (x *BJL_Sate) GetTime() int32 {
	if x != nil && x.Time != nil {
		return *x.Time
	}
	return 0
}

//用戶斷線重連下注消息
type BJL_UserBetInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserMoney *int64              `protobuf:"varint,1,req,name=UserMoney" json:"UserMoney,omitempty"`
	BetInfo   []*BJL_BroadCastBet `protobuf:"bytes,2,rep,name=BetInfo" json:"BetInfo,omitempty"`
}

func (x *BJL_UserBetInfo) Reset() {
	*x = BJL_UserBetInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_GameMsg_BJL_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BJL_UserBetInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BJL_UserBetInfo) ProtoMessage() {}

func (x *BJL_UserBetInfo) ProtoReflect() protoreflect.Message {
	mi := &file_GameMsg_BJL_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BJL_UserBetInfo.ProtoReflect.Descriptor instead.
func (*BJL_UserBetInfo) Descriptor() ([]byte, []int) {
	return file_GameMsg_BJL_proto_rawDescGZIP(), []int{2}
}

func (x *BJL_UserBetInfo) GetUserMoney() int64 {
	if x != nil && x.UserMoney != nil {
		return *x.UserMoney
	}
	return 0
}

func (x *BJL_UserBetInfo) GetBetInfo() []*BJL_BroadCastBet {
	if x != nil {
		return x.BetInfo
	}
	return nil
}

//廣播用戶下注的數組
type BJL_BroadCastBetArr struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserID          *int32              `protobuf:"varint,1,req,name=UserID" json:"UserID,omitempty"`
	BroadCastBetArr []*BJL_BroadCastBet `protobuf:"bytes,2,rep,name=BroadCastBetArr" json:"BroadCastBetArr,omitempty"`
	BetArrSelf      []*BJL_Bet          `protobuf:"bytes,3,rep,name=BetArrSelf" json:"BetArrSelf,omitempty"`
}

func (x *BJL_BroadCastBetArr) Reset() {
	*x = BJL_BroadCastBetArr{}
	if protoimpl.UnsafeEnabled {
		mi := &file_GameMsg_BJL_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BJL_BroadCastBetArr) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BJL_BroadCastBetArr) ProtoMessage() {}

func (x *BJL_BroadCastBetArr) ProtoReflect() protoreflect.Message {
	mi := &file_GameMsg_BJL_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BJL_BroadCastBetArr.ProtoReflect.Descriptor instead.
func (*BJL_BroadCastBetArr) Descriptor() ([]byte, []int) {
	return file_GameMsg_BJL_proto_rawDescGZIP(), []int{3}
}

func (x *BJL_BroadCastBetArr) GetUserID() int32 {
	if x != nil && x.UserID != nil {
		return *x.UserID
	}
	return 0
}

func (x *BJL_BroadCastBetArr) GetBroadCastBetArr() []*BJL_BroadCastBet {
	if x != nil {
		return x.BroadCastBetArr
	}
	return nil
}

func (x *BJL_BroadCastBetArr) GetBetArrSelf() []*BJL_Bet {
	if x != nil {
		return x.BetArrSelf
	}
	return nil
}

//廣播用戶下注內容數據結構
type BJL_BroadCastBet struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type  *int32 `protobuf:"varint,1,req,name=Type" json:"Type,omitempty"`
	Money *int64 `protobuf:"varint,2,req,name=Money" json:"Money,omitempty"`
}

func (x *BJL_BroadCastBet) Reset() {
	*x = BJL_BroadCastBet{}
	if protoimpl.UnsafeEnabled {
		mi := &file_GameMsg_BJL_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BJL_BroadCastBet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BJL_BroadCastBet) ProtoMessage() {}

func (x *BJL_BroadCastBet) ProtoReflect() protoreflect.Message {
	mi := &file_GameMsg_BJL_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BJL_BroadCastBet.ProtoReflect.Descriptor instead.
func (*BJL_BroadCastBet) Descriptor() ([]byte, []int) {
	return file_GameMsg_BJL_proto_rawDescGZIP(), []int{4}
}

func (x *BJL_BroadCastBet) GetType() int32 {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return 0
}

func (x *BJL_BroadCastBet) GetMoney() int64 {
	if x != nil && x.Money != nil {
		return *x.Money
	}
	return 0
}

//用戶下注數組
type BJL_BetArr struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BetArr []*BJL_Bet `protobuf:"bytes,1,rep,name=BetArr" json:"BetArr,omitempty"`
}

func (x *BJL_BetArr) Reset() {
	*x = BJL_BetArr{}
	if protoimpl.UnsafeEnabled {
		mi := &file_GameMsg_BJL_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BJL_BetArr) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BJL_BetArr) ProtoMessage() {}

func (x *BJL_BetArr) ProtoReflect() protoreflect.Message {
	mi := &file_GameMsg_BJL_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BJL_BetArr.ProtoReflect.Descriptor instead.
func (*BJL_BetArr) Descriptor() ([]byte, []int) {
	return file_GameMsg_BJL_proto_rawDescGZIP(), []int{5}
}

func (x *BJL_BetArr) GetBetArr() []*BJL_Bet {
	if x != nil {
		return x.BetArr
	}
	return nil
}

//用戶下注數據結構
type BJL_Bet struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BetType *int32 `protobuf:"varint,1,req,name=BetType" json:"BetType,omitempty"`
	Count   *int32 `protobuf:"varint,2,req,name=Count" json:"Count,omitempty"`
}

func (x *BJL_Bet) Reset() {
	*x = BJL_Bet{}
	if protoimpl.UnsafeEnabled {
		mi := &file_GameMsg_BJL_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BJL_Bet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BJL_Bet) ProtoMessage() {}

func (x *BJL_Bet) ProtoReflect() protoreflect.Message {
	mi := &file_GameMsg_BJL_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BJL_Bet.ProtoReflect.Descriptor instead.
func (*BJL_Bet) Descriptor() ([]byte, []int) {
	return file_GameMsg_BJL_proto_rawDescGZIP(), []int{6}
}

func (x *BJL_Bet) GetBetType() int32 {
	if x != nil && x.BetType != nil {
		return *x.BetType
	}
	return 0
}

func (x *BJL_Bet) GetCount() int32 {
	if x != nil && x.Count != nil {
		return *x.Count
	}
	return 0
}

//百家樂下注的結果
type BJL_BetRet struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ret         *int32     `protobuf:"varint,1,req,name=Ret" json:"Ret,omitempty"`                //0下注成功，-1用戶金額不足，-2下注的類型未找到，-3莊家不能下注，-4此類下注已達到上限，-6下注方位限紅
	Money       *int64     `protobuf:"varint,2,req,name=Money" json:"Money,omitempty"`            //用戶的錢，下注以後的金額。
	Type        *int32     `protobuf:"varint,3,opt,name=Type" json:"Type,omitempty"`              //下注超過限製的下注類型
	BetArr      []*BJL_Bet `protobuf:"bytes,4,rep,name=BetArr" json:"BetArr,omitempty"`           //用戶下注數據
	UserID      *int32     `protobuf:"varint,5,req,name=UserID" json:"UserID,omitempty"`          //用戶id
	TotalBetArr []*BJL_Bet `protobuf:"bytes,6,rep,name=TotalBetArr" json:"TotalBetArr,omitempty"` //每區的總下注
}

func (x *BJL_BetRet) Reset() {
	*x = BJL_BetRet{}
	if protoimpl.UnsafeEnabled {
		mi := &file_GameMsg_BJL_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BJL_BetRet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BJL_BetRet) ProtoMessage() {}

func (x *BJL_BetRet) ProtoReflect() protoreflect.Message {
	mi := &file_GameMsg_BJL_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BJL_BetRet.ProtoReflect.Descriptor instead.
func (*BJL_BetRet) Descriptor() ([]byte, []int) {
	return file_GameMsg_BJL_proto_rawDescGZIP(), []int{7}
}

func (x *BJL_BetRet) GetRet() int32 {
	if x != nil && x.Ret != nil {
		return *x.Ret
	}
	return 0
}

func (x *BJL_BetRet) GetMoney() int64 {
	if x != nil && x.Money != nil {
		return *x.Money
	}
	return 0
}

func (x *BJL_BetRet) GetType() int32 {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return 0
}

func (x *BJL_BetRet) GetBetArr() []*BJL_Bet {
	if x != nil {
		return x.BetArr
	}
	return nil
}

func (x *BJL_BetRet) GetUserID() int32 {
	if x != nil && x.UserID != nil {
		return *x.UserID
	}
	return 0
}

func (x *BJL_BetRet) GetTotalBetArr() []*BJL_Bet {
	if x != nil {
		return x.TotalBetArr
	}
	return nil
}

//遊戲撲克結果
type BJL_GameResultPoker struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ZhuangPoker []*BJL_Poker `protobuf:"bytes,1,rep,name=ZhuangPoker" json:"ZhuangPoker,omitempty"` //莊家撲克牌
	XianPoker   []*BJL_Poker `protobuf:"bytes,2,rep,name=XianPoker" json:"XianPoker,omitempty"`     //閒家撲克牌
	ZuHe        *uint32      `protobuf:"varint,3,req,name=ZuHe" json:"ZuHe,omitempty"`              //組合結果
}

func (x *BJL_GameResultPoker) Reset() {
	*x = BJL_GameResultPoker{}
	if protoimpl.UnsafeEnabled {
		mi := &file_GameMsg_BJL_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BJL_GameResultPoker) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BJL_GameResultPoker) ProtoMessage() {}

func (x *BJL_GameResultPoker) ProtoReflect() protoreflect.Message {
	mi := &file_GameMsg_BJL_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BJL_GameResultPoker.ProtoReflect.Descriptor instead.
func (*BJL_GameResultPoker) Descriptor() ([]byte, []int) {
	return file_GameMsg_BJL_proto_rawDescGZIP(), []int{8}
}

func (x *BJL_GameResultPoker) GetZhuangPoker() []*BJL_Poker {
	if x != nil {
		return x.ZhuangPoker
	}
	return nil
}

func (x *BJL_GameResultPoker) GetXianPoker() []*BJL_Poker {
	if x != nil {
		return x.XianPoker
	}
	return nil
}

func (x *BJL_GameResultPoker) GetZuHe() uint32 {
	if x != nil && x.ZuHe != nil {
		return *x.ZuHe
	}
	return 0
}

type BJL_GameResultOneUserWin struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserID   *int32 `protobuf:"varint,1,req,name=UserID" json:"UserID,omitempty"`     //玩家ID
	WinMoney *int64 `protobuf:"varint,2,req,name=WinMoney" json:"WinMoney,omitempty"` //輸贏錢
}

func (x *BJL_GameResultOneUserWin) Reset() {
	*x = BJL_GameResultOneUserWin{}
	if protoimpl.UnsafeEnabled {
		mi := &file_GameMsg_BJL_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BJL_GameResultOneUserWin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BJL_GameResultOneUserWin) ProtoMessage() {}

func (x *BJL_GameResultOneUserWin) ProtoReflect() protoreflect.Message {
	mi := &file_GameMsg_BJL_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BJL_GameResultOneUserWin.ProtoReflect.Descriptor instead.
func (*BJL_GameResultOneUserWin) Descriptor() ([]byte, []int) {
	return file_GameMsg_BJL_proto_rawDescGZIP(), []int{9}
}

func (x *BJL_GameResultOneUserWin) GetUserID() int32 {
	if x != nil && x.UserID != nil {
		return *x.UserID
	}
	return 0
}

func (x *BJL_GameResultOneUserWin) GetWinMoney() int64 {
	if x != nil && x.WinMoney != nil {
		return *x.WinMoney
	}
	return 0
}

//遊戲用戶贏錢結果 BJLGameResultTOPNWin=10019
type BJL_GameResultTOPNWin struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ZhuangWin   *int64                      `protobuf:"varint,1,req,name=ZhuangWin" json:"ZhuangWin,omitempty"`
	SelfWin     *int64                      `protobuf:"varint,2,req,name=SelfWin" json:"SelfWin,omitempty"`
	ZuHe        *uint32                     `protobuf:"varint,3,req,name=ZuHe" json:"ZuHe,omitempty"`              //組合結果
	WinUserInfo []*BJL_GameResultOneUserWin `protobuf:"bytes,4,rep,name=WinUserInfo" json:"WinUserInfo,omitempty"` //所有人輸贏數據
}

func (x *BJL_GameResultTOPNWin) Reset() {
	*x = BJL_GameResultTOPNWin{}
	if protoimpl.UnsafeEnabled {
		mi := &file_GameMsg_BJL_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BJL_GameResultTOPNWin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BJL_GameResultTOPNWin) ProtoMessage() {}

func (x *BJL_GameResultTOPNWin) ProtoReflect() protoreflect.Message {
	mi := &file_GameMsg_BJL_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BJL_GameResultTOPNWin.ProtoReflect.Descriptor instead.
func (*BJL_GameResultTOPNWin) Descriptor() ([]byte, []int) {
	return file_GameMsg_BJL_proto_rawDescGZIP(), []int{10}
}

func (x *BJL_GameResultTOPNWin) GetZhuangWin() int64 {
	if x != nil && x.ZhuangWin != nil {
		return *x.ZhuangWin
	}
	return 0
}

func (x *BJL_GameResultTOPNWin) GetSelfWin() int64 {
	if x != nil && x.SelfWin != nil {
		return *x.SelfWin
	}
	return 0
}

func (x *BJL_GameResultTOPNWin) GetZuHe() uint32 {
	if x != nil && x.ZuHe != nil {
		return *x.ZuHe
	}
	return 0
}

func (x *BJL_GameResultTOPNWin) GetWinUserInfo() []*BJL_GameResultOneUserWin {
	if x != nil {
		return x.WinUserInfo
	}
	return nil
}

//遊戲用戶贏錢結果
type BJL_GameResultUserMoney struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ZhuangWin   *int64            `protobuf:"varint,1,req,name=ZhuangWin" json:"ZhuangWin,omitempty"`
	SelfWin     *int64            `protobuf:"varint,2,req,name=SelfWin" json:"SelfWin,omitempty"`
	WinUserInfo []*BJL_WinUerInfo `protobuf:"bytes,3,rep,name=WinUserInfo" json:"WinUserInfo,omitempty"` //贏錢前三名的人信息
}

func (x *BJL_GameResultUserMoney) Reset() {
	*x = BJL_GameResultUserMoney{}
	if protoimpl.UnsafeEnabled {
		mi := &file_GameMsg_BJL_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BJL_GameResultUserMoney) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BJL_GameResultUserMoney) ProtoMessage() {}

func (x *BJL_GameResultUserMoney) ProtoReflect() protoreflect.Message {
	mi := &file_GameMsg_BJL_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BJL_GameResultUserMoney.ProtoReflect.Descriptor instead.
func (*BJL_GameResultUserMoney) Descriptor() ([]byte, []int) {
	return file_GameMsg_BJL_proto_rawDescGZIP(), []int{11}
}

func (x *BJL_GameResultUserMoney) GetZhuangWin() int64 {
	if x != nil && x.ZhuangWin != nil {
		return *x.ZhuangWin
	}
	return 0
}

func (x *BJL_GameResultUserMoney) GetSelfWin() int64 {
	if x != nil && x.SelfWin != nil {
		return *x.SelfWin
	}
	return 0
}

func (x *BJL_GameResultUserMoney) GetWinUserInfo() []*BJL_WinUerInfo {
	if x != nil {
		return x.WinUserInfo
	}
	return nil
}

//贏錢玩家信息
type BJL_WinUerInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserName *string `protobuf:"bytes,1,req,name=UserName" json:"UserName,omitempty"`
	Win      *int64  `protobuf:"varint,2,req,name=Win" json:"Win,omitempty"`
}

func (x *BJL_WinUerInfo) Reset() {
	*x = BJL_WinUerInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_GameMsg_BJL_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BJL_WinUerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BJL_WinUerInfo) ProtoMessage() {}

func (x *BJL_WinUerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_GameMsg_BJL_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BJL_WinUerInfo.ProtoReflect.Descriptor instead.
func (*BJL_WinUerInfo) Descriptor() ([]byte, []int) {
	return file_GameMsg_BJL_proto_rawDescGZIP(), []int{12}
}

func (x *BJL_WinUerInfo) GetUserName() string {
	if x != nil && x.UserName != nil {
		return *x.UserName
	}
	return ""
}

func (x *BJL_WinUerInfo) GetWin() int64 {
	if x != nil && x.Win != nil {
		return *x.Win
	}
	return 0
}

//百家樂牌的點數和花色
type BJL_Poker struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Color      *int32  `protobuf:"varint,1,req,name=Color" json:"Color,omitempty"`          //從0-3，分別表示黑桃，紅桃，櫻花，方塊
	Number     *int32  `protobuf:"varint,2,req,name=Number" json:"Number,omitempty"`        //數字1-13，A-K
	Index      *int32  `protobuf:"varint,3,opt,name=Index" json:"Index,omitempty"`          //編號
	PlainText  *string `protobuf:"bytes,4,opt,name=PlainText" json:"PlainText,omitempty"`   // 明文
	EncodeText *string `protobuf:"bytes,5,opt,name=EncodeText" json:"EncodeText,omitempty"` // 加密
}

func (x *BJL_Poker) Reset() {
	*x = BJL_Poker{}
	if protoimpl.UnsafeEnabled {
		mi := &file_GameMsg_BJL_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BJL_Poker) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BJL_Poker) ProtoMessage() {}

func (x *BJL_Poker) ProtoReflect() protoreflect.Message {
	mi := &file_GameMsg_BJL_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BJL_Poker.ProtoReflect.Descriptor instead.
func (*BJL_Poker) Descriptor() ([]byte, []int) {
	return file_GameMsg_BJL_proto_rawDescGZIP(), []int{13}
}

func (x *BJL_Poker) GetColor() int32 {
	if x != nil && x.Color != nil {
		return *x.Color
	}
	return 0
}

func (x *BJL_Poker) GetNumber() int32 {
	if x != nil && x.Number != nil {
		return *x.Number
	}
	return 0
}

func (x *BJL_Poker) GetIndex() int32 {
	if x != nil && x.Index != nil {
		return *x.Index
	}
	return 0
}

func (x *BJL_Poker) GetPlainText() string {
	if x != nil && x.PlainText != nil {
		return *x.PlainText
	}
	return ""
}

func (x *BJL_Poker) GetEncodeText() string {
	if x != nil && x.EncodeText != nil {
		return *x.EncodeText
	}
	return ""
}

type BJL_Cards struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cards []*BJL_GameResultPoker `protobuf:"bytes,1,rep,name=Cards" json:"Cards,omitempty"`
}

func (x *BJL_Cards) Reset() {
	*x = BJL_Cards{}
	if protoimpl.UnsafeEnabled {
		mi := &file_GameMsg_BJL_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BJL_Cards) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BJL_Cards) ProtoMessage() {}

func (x *BJL_Cards) ProtoReflect() protoreflect.Message {
	mi := &file_GameMsg_BJL_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BJL_Cards.ProtoReflect.Descriptor instead.
func (*BJL_Cards) Descriptor() ([]byte, []int) {
	return file_GameMsg_BJL_proto_rawDescGZIP(), []int{14}
}

func (x *BJL_Cards) GetCards() []*BJL_GameResultPoker {
	if x != nil {
		return x.Cards
	}
	return nil
}

type BJL_GamResultInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ResultPoke *BJL_GameResultPoker `protobuf:"bytes,1,req,name=ResultPoke" json:"ResultPoke,omitempty"`
	TableNo    *int32               `protobuf:"varint,2,req,name=TableNo" json:"TableNo,omitempty"` //桌子ID
}

func (x *BJL_GamResultInfo) Reset() {
	*x = BJL_GamResultInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_GameMsg_BJL_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BJL_GamResultInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BJL_GamResultInfo) ProtoMessage() {}

func (x *BJL_GamResultInfo) ProtoReflect() protoreflect.Message {
	mi := &file_GameMsg_BJL_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BJL_GamResultInfo.ProtoReflect.Descriptor instead.
func (*BJL_GamResultInfo) Descriptor() ([]byte, []int) {
	return file_GameMsg_BJL_proto_rawDescGZIP(), []int{15}
}

func (x *BJL_GamResultInfo) GetResultPoke() *BJL_GameResultPoker {
	if x != nil {
		return x.ResultPoke
	}
	return nil
}

func (x *BJL_GamResultInfo) GetTableNo() int32 {
	if x != nil && x.TableNo != nil {
		return *x.TableNo
	}
	return 0
}

//前20次開出的牌
type BJL_ResultCardList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CardList []*BJL_GameResultPoker `protobuf:"bytes,1,rep,name=CardList" json:"CardList,omitempty"`
	TableNo  *int32                 `protobuf:"varint,2,opt,name=TableNo" json:"TableNo,omitempty"` //桌子ID
}

func (x *BJL_ResultCardList) Reset() {
	*x = BJL_ResultCardList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_GameMsg_BJL_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BJL_ResultCardList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BJL_ResultCardList) ProtoMessage() {}

func (x *BJL_ResultCardList) ProtoReflect() protoreflect.Message {
	mi := &file_GameMsg_BJL_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BJL_ResultCardList.ProtoReflect.Descriptor instead.
func (*BJL_ResultCardList) Descriptor() ([]byte, []int) {
	return file_GameMsg_BJL_proto_rawDescGZIP(), []int{16}
}

func (x *BJL_ResultCardList) GetCardList() []*BJL_GameResultPoker {
	if x != nil {
		return x.CardList
	}
	return nil
}

func (x *BJL_ResultCardList) GetTableNo() int32 {
	if x != nil && x.TableNo != nil {
		return *x.TableNo
	}
	return 0
}

//上莊結果
type BJL_ShangzhuangRet struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ret *int32 `protobuf:"varint,1,req,name=ret" json:"ret,omitempty"` //值為1時下莊成功，值為0表示上莊成功，值為-1時上莊失敗資金不足，值為-2時已經在上莊列表中。
}

func (x *BJL_ShangzhuangRet) Reset() {
	*x = BJL_ShangzhuangRet{}
	if protoimpl.UnsafeEnabled {
		mi := &file_GameMsg_BJL_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BJL_ShangzhuangRet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BJL_ShangzhuangRet) ProtoMessage() {}

func (x *BJL_ShangzhuangRet) ProtoReflect() protoreflect.Message {
	mi := &file_GameMsg_BJL_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BJL_ShangzhuangRet.ProtoReflect.Descriptor instead.
func (*BJL_ShangzhuangRet) Descriptor() ([]byte, []int) {
	return file_GameMsg_BJL_proto_rawDescGZIP(), []int{17}
}

func (x *BJL_ShangzhuangRet) GetRet() int32 {
	if x != nil && x.Ret != nil {
		return *x.Ret
	}
	return 0
}

//是否上莊
type BJL_ShangZhuang struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IsShangZhuang *bool `protobuf:"varint,1,req,name=IsShangZhuang" json:"IsShangZhuang,omitempty"`
}

func (x *BJL_ShangZhuang) Reset() {
	*x = BJL_ShangZhuang{}
	if protoimpl.UnsafeEnabled {
		mi := &file_GameMsg_BJL_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BJL_ShangZhuang) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BJL_ShangZhuang) ProtoMessage() {}

func (x *BJL_ShangZhuang) ProtoReflect() protoreflect.Message {
	mi := &file_GameMsg_BJL_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BJL_ShangZhuang.ProtoReflect.Descriptor instead.
func (*BJL_ShangZhuang) Descriptor() ([]byte, []int) {
	return file_GameMsg_BJL_proto_rawDescGZIP(), []int{18}
}

func (x *BJL_ShangZhuang) GetIsShangZhuang() bool {
	if x != nil && x.IsShangZhuang != nil {
		return *x.IsShangZhuang
	}
	return false
}

//莊家信息
type BJL_ZhuangInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserID      *int32      `protobuf:"varint,1,req,name=UserID" json:"UserID,omitempty"`
	LastTurn    *int32      `protobuf:"varint,2,req,name=LastTurn" json:"LastTurn,omitempty"`
	UserInfo    []*GameUser `protobuf:"bytes,3,rep,name=UserInfo" json:"UserInfo,omitempty"`
	UpdateScore *int64      `protobuf:"varint,4,opt,name=UpdateScore" json:"UpdateScore,omitempty"` //上莊期間的輸贏
}

func (x *BJL_ZhuangInfo) Reset() {
	*x = BJL_ZhuangInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_GameMsg_BJL_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BJL_ZhuangInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BJL_ZhuangInfo) ProtoMessage() {}

func (x *BJL_ZhuangInfo) ProtoReflect() protoreflect.Message {
	mi := &file_GameMsg_BJL_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BJL_ZhuangInfo.ProtoReflect.Descriptor instead.
func (*BJL_ZhuangInfo) Descriptor() ([]byte, []int) {
	return file_GameMsg_BJL_proto_rawDescGZIP(), []int{19}
}

func (x *BJL_ZhuangInfo) GetUserID() int32 {
	if x != nil && x.UserID != nil {
		return *x.UserID
	}
	return 0
}

func (x *BJL_ZhuangInfo) GetLastTurn() int32 {
	if x != nil && x.LastTurn != nil {
		return *x.LastTurn
	}
	return 0
}

func (x *BJL_ZhuangInfo) GetUserInfo() []*GameUser {
	if x != nil {
		return x.UserInfo
	}
	return nil
}

func (x *BJL_ZhuangInfo) GetUpdateScore() int64 {
	if x != nil && x.UpdateScore != nil {
		return *x.UpdateScore
	}
	return 0
}

//上莊列表
type BJL_ZhuangList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserInfo []*GameUser `protobuf:"bytes,1,rep,name=UserInfo" json:"UserInfo,omitempty"`
}

func (x *BJL_ZhuangList) Reset() {
	*x = BJL_ZhuangList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_GameMsg_BJL_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BJL_ZhuangList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BJL_ZhuangList) ProtoMessage() {}

func (x *BJL_ZhuangList) ProtoReflect() protoreflect.Message {
	mi := &file_GameMsg_BJL_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BJL_ZhuangList.ProtoReflect.Descriptor instead.
func (*BJL_ZhuangList) Descriptor() ([]byte, []int) {
	return file_GameMsg_BJL_proto_rawDescGZIP(), []int{20}
}

func (x *BJL_ZhuangList) GetUserInfo() []*GameUser {
	if x != nil {
		return x.UserInfo
	}
	return nil
}

//清除結果回應消息
type BJL_BetClearRet struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Money *int64 `protobuf:"varint,1,req,name=Money" json:"Money,omitempty"` //當前的錢
	Ret   *int32 `protobuf:"varint,2,req,name=Ret" json:"Ret,omitempty"`     //清除結果-1，清理失敗，達到清理上限，0清理成功
}

func (x *BJL_BetClearRet) Reset() {
	*x = BJL_BetClearRet{}
	if protoimpl.UnsafeEnabled {
		mi := &file_GameMsg_BJL_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BJL_BetClearRet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BJL_BetClearRet) ProtoMessage() {}

func (x *BJL_BetClearRet) ProtoReflect() protoreflect.Message {
	mi := &file_GameMsg_BJL_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BJL_BetClearRet.ProtoReflect.Descriptor instead.
func (*BJL_BetClearRet) Descriptor() ([]byte, []int) {
	return file_GameMsg_BJL_proto_rawDescGZIP(), []int{21}
}

func (x *BJL_BetClearRet) GetMoney() int64 {
	if x != nil && x.Money != nil {
		return *x.Money
	}
	return 0
}

func (x *BJL_BetClearRet) GetRet() int32 {
	if x != nil && x.Ret != nil {
		return *x.Ret
	}
	return 0
}

//進入遊戲玩家列表 BJLGameUserScoreRank=10018
type BJL_GameUserScoreRankList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserList []*GameUser `protobuf:"bytes,1,rep,name=UserList" json:"UserList,omitempty"` //進入本局遊戲時金幣topn
}

func (x *BJL_GameUserScoreRankList) Reset() {
	*x = BJL_GameUserScoreRankList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_GameMsg_BJL_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BJL_GameUserScoreRankList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BJL_GameUserScoreRankList) ProtoMessage() {}

func (x *BJL_GameUserScoreRankList) ProtoReflect() protoreflect.Message {
	mi := &file_GameMsg_BJL_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BJL_GameUserScoreRankList.ProtoReflect.Descriptor instead.
func (*BJL_GameUserScoreRankList) Descriptor() ([]byte, []int) {
	return file_GameMsg_BJL_proto_rawDescGZIP(), []int{22}
}

func (x *BJL_GameUserScoreRankList) GetUserList() []*GameUser {
	if x != nil {
		return x.UserList
	}
	return nil
}

//房間桌子信息
type BJL_TableInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TableNo        *int32 `protobuf:"varint,1,req,name=TableNo" json:"TableNo,omitempty"`               //桌子ID
	ShoeNo         *int32 `protobuf:"varint,2,req,name=ShoeNo" json:"ShoeNo,omitempty"`                 //牌靴序號
	GameNo         *int32 `protobuf:"varint,3,req,name=GameNo" json:"GameNo,omitempty"`                 //牌局序號
	FirstCardIndex *int32 `protobuf:"varint,4,req,name=FirstCardIndex" json:"FirstCardIndex,omitempty"` //此牌局第一張卡的序號
	MinLimit       *int32 `protobuf:"varint,5,req,name=MinLimit" json:"MinLimit,omitempty"`             //最小下注金額
	MaxLimit       *int32 `protobuf:"varint,6,req,name=MaxLimit" json:"MaxLimit,omitempty"`             //最大下注金額
	TableLimit     *int32 `protobuf:"varint,7,req,name=TableLimit" json:"TableLimit,omitempty"`         //限紅
	BankerLimit    *int32 `protobuf:"varint,8,req,name=BankerLimit" json:"BankerLimit,omitempty"`       //莊家最大下注金額
	PairLimit      *int32 `protobuf:"varint,9,req,name=PairLimit" json:"PairLimit,omitempty"`           //對子最大下注金額
	TieLimit       *int32 `protobuf:"varint,10,req,name=TieLimit" json:"TieLimit,omitempty"`            //和局最大下注金額
	GameLmit       *int32 `protobuf:"varint,11,opt,name=GameLmit" json:"GameLmit,omitempty"`            //牌靴的最大局數限制
}

func (x *BJL_TableInfo) Reset() {
	*x = BJL_TableInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_GameMsg_BJL_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BJL_TableInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BJL_TableInfo) ProtoMessage() {}

func (x *BJL_TableInfo) ProtoReflect() protoreflect.Message {
	mi := &file_GameMsg_BJL_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BJL_TableInfo.ProtoReflect.Descriptor instead.
func (*BJL_TableInfo) Descriptor() ([]byte, []int) {
	return file_GameMsg_BJL_proto_rawDescGZIP(), []int{23}
}

func (x *BJL_TableInfo) GetTableNo() int32 {
	if x != nil && x.TableNo != nil {
		return *x.TableNo
	}
	return 0
}

func (x *BJL_TableInfo) GetShoeNo() int32 {
	if x != nil && x.ShoeNo != nil {
		return *x.ShoeNo
	}
	return 0
}

func (x *BJL_TableInfo) GetGameNo() int32 {
	if x != nil && x.GameNo != nil {
		return *x.GameNo
	}
	return 0
}

func (x *BJL_TableInfo) GetFirstCardIndex() int32 {
	if x != nil && x.FirstCardIndex != nil {
		return *x.FirstCardIndex
	}
	return 0
}

func (x *BJL_TableInfo) GetMinLimit() int32 {
	if x != nil && x.MinLimit != nil {
		return *x.MinLimit
	}
	return 0
}

func (x *BJL_TableInfo) GetMaxLimit() int32 {
	if x != nil && x.MaxLimit != nil {
		return *x.MaxLimit
	}
	return 0
}

func (x *BJL_TableInfo) GetTableLimit() int32 {
	if x != nil && x.TableLimit != nil {
		return *x.TableLimit
	}
	return 0
}

func (x *BJL_TableInfo) GetBankerLimit() int32 {
	if x != nil && x.BankerLimit != nil {
		return *x.BankerLimit
	}
	return 0
}

func (x *BJL_TableInfo) GetPairLimit() int32 {
	if x != nil && x.PairLimit != nil {
		return *x.PairLimit
	}
	return 0
}

func (x *BJL_TableInfo) GetTieLimit() int32 {
	if x != nil && x.TieLimit != nil {
		return *x.TieLimit
	}
	return 0
}

func (x *BJL_TableInfo) GetGameLmit() int32 {
	if x != nil && x.GameLmit != nil {
		return *x.GameLmit
	}
	return 0
}

var File_GameMsg_BJL_proto protoreflect.FileDescriptor

var file_GameMsg_BJL_proto_rawDesc = []byte{
	0x0a, 0x11, 0x47, 0x61, 0x6d, 0x65, 0x4d, 0x73, 0x67, 0x5f, 0x42, 0x4a, 0x4c, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x08, 0x6e, 0x65, 0x74, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0d, 0x47,
	0x61, 0x6d, 0x65, 0x4d, 0x73, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x8d, 0x02, 0x0a,
	0x0b, 0x42, 0x4a, 0x4c, 0x5f, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x12, 0x1a, 0x0a, 0x08,
	0x42, 0x65, 0x74, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x05, 0x52, 0x08,
	0x42, 0x65, 0x74, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x42, 0x65, 0x74, 0x4d,
	0x6f, 0x6e, 0x65, 0x79, 0x18, 0x02, 0x20, 0x02, 0x28, 0x05, 0x52, 0x08, 0x42, 0x65, 0x74, 0x4d,
	0x6f, 0x6e, 0x65, 0x79, 0x12, 0x24, 0x0a, 0x0d, 0x42, 0x65, 0x74, 0x4d, 0x6f, 0x6e, 0x65, 0x79,
	0x4c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x03, 0x20, 0x02, 0x28, 0x03, 0x52, 0x0d, 0x42, 0x65, 0x74,
	0x4d, 0x6f, 0x6e, 0x65, 0x79, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x12, 0x20, 0x0a, 0x0b, 0x5a, 0x68,
	0x75, 0x61, 0x6e, 0x67, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x04, 0x20, 0x02, 0x28, 0x03, 0x52,
	0x0b, 0x5a, 0x68, 0x75, 0x61, 0x6e, 0x67, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x12, 0x1c, 0x0a, 0x09,
	0x4d, 0x61, 0x78, 0x5a, 0x68, 0x75, 0x61, 0x6e, 0x67, 0x18, 0x05, 0x20, 0x02, 0x28, 0x05, 0x52,
	0x09, 0x4d, 0x61, 0x78, 0x5a, 0x68, 0x75, 0x61, 0x6e, 0x67, 0x12, 0x20, 0x0a, 0x0b, 0x43, 0x61,
	0x6e, 0x42, 0x65, 0x74, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x0b, 0x43, 0x61, 0x6e, 0x42, 0x65, 0x74, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x12, 0x22, 0x0a, 0x0c,
	0x42, 0x65, 0x74, 0x54, 0x79, 0x70, 0x65, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x07, 0x20, 0x03,
	0x28, 0x03, 0x52, 0x0c, 0x42, 0x65, 0x74, 0x54, 0x79, 0x70, 0x65, 0x4c, 0x69, 0x6d, 0x69, 0x74,
	0x12, 0x1a, 0x0a, 0x08, 0x49, 0x73, 0x43, 0x61, 0x6e, 0x42, 0x65, 0x74, 0x18, 0x08, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x08, 0x49, 0x73, 0x43, 0x61, 0x6e, 0x42, 0x65, 0x74, 0x22, 0x34, 0x0a, 0x08,
	0x42, 0x4a, 0x4c, 0x5f, 0x53, 0x61, 0x74, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x53, 0x74, 0x61, 0x74,
	0x65, 0x18, 0x01, 0x20, 0x02, 0x28, 0x05, 0x52, 0x05, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x12,
	0x0a, 0x04, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x02, 0x28, 0x05, 0x52, 0x04, 0x54, 0x69,
	0x6d, 0x65, 0x22, 0x65, 0x0a, 0x0f, 0x42, 0x4a, 0x4c, 0x5f, 0x55, 0x73, 0x65, 0x72, 0x42, 0x65,
	0x74, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x1c, 0x0a, 0x09, 0x55, 0x73, 0x65, 0x72, 0x4d, 0x6f, 0x6e,
	0x65, 0x79, 0x18, 0x01, 0x20, 0x02, 0x28, 0x03, 0x52, 0x09, 0x55, 0x73, 0x65, 0x72, 0x4d, 0x6f,
	0x6e, 0x65, 0x79, 0x12, 0x34, 0x0a, 0x07, 0x42, 0x65, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x18, 0x02,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x6e, 0x65, 0x74, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x42, 0x4a, 0x4c, 0x5f, 0x42, 0x72, 0x6f, 0x61, 0x64, 0x43, 0x61, 0x73, 0x74, 0x42, 0x65, 0x74,
	0x52, 0x07, 0x42, 0x65, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x22, 0xa6, 0x01, 0x0a, 0x13, 0x42, 0x4a,
	0x4c, 0x5f, 0x42, 0x72, 0x6f, 0x61, 0x64, 0x43, 0x61, 0x73, 0x74, 0x42, 0x65, 0x74, 0x41, 0x72,
	0x72, 0x12, 0x16, 0x0a, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x18, 0x01, 0x20, 0x02, 0x28,
	0x05, 0x52, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x12, 0x44, 0x0a, 0x0f, 0x42, 0x72, 0x6f,
	0x61, 0x64, 0x43, 0x61, 0x73, 0x74, 0x42, 0x65, 0x74, 0x41, 0x72, 0x72, 0x18, 0x02, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x6e, 0x65, 0x74, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x42, 0x4a,
	0x4c, 0x5f, 0x42, 0x72, 0x6f, 0x61, 0x64, 0x43, 0x61, 0x73, 0x74, 0x42, 0x65, 0x74, 0x52, 0x0f,
	0x42, 0x72, 0x6f, 0x61, 0x64, 0x43, 0x61, 0x73, 0x74, 0x42, 0x65, 0x74, 0x41, 0x72, 0x72, 0x12,
	0x31, 0x0a, 0x0a, 0x42, 0x65, 0x74, 0x41, 0x72, 0x72, 0x53, 0x65, 0x6c, 0x66, 0x18, 0x03, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x6e, 0x65, 0x74, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x42,
	0x4a, 0x4c, 0x5f, 0x42, 0x65, 0x74, 0x52, 0x0a, 0x42, 0x65, 0x74, 0x41, 0x72, 0x72, 0x53, 0x65,
	0x6c, 0x66, 0x22, 0x3c, 0x0a, 0x10, 0x42, 0x4a, 0x4c, 0x5f, 0x42, 0x72, 0x6f, 0x61, 0x64, 0x43,
	0x61, 0x73, 0x74, 0x42, 0x65, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x54, 0x79, 0x70, 0x65, 0x18, 0x01,
	0x20, 0x02, 0x28, 0x05, 0x52, 0x04, 0x54, 0x79, 0x70, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x4d, 0x6f,
	0x6e, 0x65, 0x79, 0x18, 0x02, 0x20, 0x02, 0x28, 0x03, 0x52, 0x05, 0x4d, 0x6f, 0x6e, 0x65, 0x79,
	0x22, 0x37, 0x0a, 0x0a, 0x42, 0x4a, 0x4c, 0x5f, 0x42, 0x65, 0x74, 0x41, 0x72, 0x72, 0x12, 0x29,
	0x0a, 0x06, 0x42, 0x65, 0x74, 0x41, 0x72, 0x72, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x11,
	0x2e, 0x6e, 0x65, 0x74, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x42, 0x4a, 0x4c, 0x5f, 0x42, 0x65,
	0x74, 0x52, 0x06, 0x42, 0x65, 0x74, 0x41, 0x72, 0x72, 0x22, 0x39, 0x0a, 0x07, 0x42, 0x4a, 0x4c,
	0x5f, 0x42, 0x65, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x42, 0x65, 0x74, 0x54, 0x79, 0x70, 0x65, 0x18,
	0x01, 0x20, 0x02, 0x28, 0x05, 0x52, 0x07, 0x42, 0x65, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x14,
	0x0a, 0x05, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x02, 0x28, 0x05, 0x52, 0x05, 0x43,
	0x6f, 0x75, 0x6e, 0x74, 0x22, 0xc0, 0x01, 0x0a, 0x0a, 0x42, 0x4a, 0x4c, 0x5f, 0x42, 0x65, 0x74,
	0x52, 0x65, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x52, 0x65, 0x74, 0x18, 0x01, 0x20, 0x02, 0x28, 0x05,
	0x52, 0x03, 0x52, 0x65, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x4d, 0x6f, 0x6e, 0x65, 0x79, 0x18, 0x02,
	0x20, 0x02, 0x28, 0x03, 0x52, 0x05, 0x4d, 0x6f, 0x6e, 0x65, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x54,
	0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x54, 0x79, 0x70, 0x65, 0x12,
	0x29, 0x0a, 0x06, 0x42, 0x65, 0x74, 0x41, 0x72, 0x72, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x11, 0x2e, 0x6e, 0x65, 0x74, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x42, 0x4a, 0x4c, 0x5f, 0x42,
	0x65, 0x74, 0x52, 0x06, 0x42, 0x65, 0x74, 0x41, 0x72, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x55, 0x73,
	0x65, 0x72, 0x49, 0x44, 0x18, 0x05, 0x20, 0x02, 0x28, 0x05, 0x52, 0x06, 0x55, 0x73, 0x65, 0x72,
	0x49, 0x44, 0x12, 0x33, 0x0a, 0x0b, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x42, 0x65, 0x74, 0x41, 0x72,
	0x72, 0x18, 0x06, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x6e, 0x65, 0x74, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x42, 0x4a, 0x4c, 0x5f, 0x42, 0x65, 0x74, 0x52, 0x0b, 0x54, 0x6f, 0x74, 0x61,
	0x6c, 0x42, 0x65, 0x74, 0x41, 0x72, 0x72, 0x22, 0x93, 0x01, 0x0a, 0x13, 0x42, 0x4a, 0x4c, 0x5f,
	0x47, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x50, 0x6f, 0x6b, 0x65, 0x72, 0x12,
	0x35, 0x0a, 0x0b, 0x5a, 0x68, 0x75, 0x61, 0x6e, 0x67, 0x50, 0x6f, 0x6b, 0x65, 0x72, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x6e, 0x65, 0x74, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x42, 0x4a, 0x4c, 0x5f, 0x50, 0x6f, 0x6b, 0x65, 0x72, 0x52, 0x0b, 0x5a, 0x68, 0x75, 0x61, 0x6e,
	0x67, 0x50, 0x6f, 0x6b, 0x65, 0x72, 0x12, 0x31, 0x0a, 0x09, 0x58, 0x69, 0x61, 0x6e, 0x50, 0x6f,
	0x6b, 0x65, 0x72, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x6e, 0x65, 0x74, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x42, 0x4a, 0x4c, 0x5f, 0x50, 0x6f, 0x6b, 0x65, 0x72, 0x52, 0x09,
	0x58, 0x69, 0x61, 0x6e, 0x50, 0x6f, 0x6b, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x5a, 0x75, 0x48,
	0x65, 0x18, 0x03, 0x20, 0x02, 0x28, 0x0d, 0x52, 0x04, 0x5a, 0x75, 0x48, 0x65, 0x22, 0x4e, 0x0a,
	0x18, 0x42, 0x4a, 0x4c, 0x5f, 0x47, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x4f,
	0x6e, 0x65, 0x55, 0x73, 0x65, 0x72, 0x57, 0x69, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x55, 0x73, 0x65,
	0x72, 0x49, 0x44, 0x18, 0x01, 0x20, 0x02, 0x28, 0x05, 0x52, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49,
	0x44, 0x12, 0x1a, 0x0a, 0x08, 0x57, 0x69, 0x6e, 0x4d, 0x6f, 0x6e, 0x65, 0x79, 0x18, 0x02, 0x20,
	0x02, 0x28, 0x03, 0x52, 0x08, 0x57, 0x69, 0x6e, 0x4d, 0x6f, 0x6e, 0x65, 0x79, 0x22, 0xa9, 0x01,
	0x0a, 0x15, 0x42, 0x4a, 0x4c, 0x5f, 0x47, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74,
	0x54, 0x4f, 0x50, 0x4e, 0x57, 0x69, 0x6e, 0x12, 0x1c, 0x0a, 0x09, 0x5a, 0x68, 0x75, 0x61, 0x6e,
	0x67, 0x57, 0x69, 0x6e, 0x18, 0x01, 0x20, 0x02, 0x28, 0x03, 0x52, 0x09, 0x5a, 0x68, 0x75, 0x61,
	0x6e, 0x67, 0x57, 0x69, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x53, 0x65, 0x6c, 0x66, 0x57, 0x69, 0x6e,
	0x18, 0x02, 0x20, 0x02, 0x28, 0x03, 0x52, 0x07, 0x53, 0x65, 0x6c, 0x66, 0x57, 0x69, 0x6e, 0x12,
	0x12, 0x0a, 0x04, 0x5a, 0x75, 0x48, 0x65, 0x18, 0x03, 0x20, 0x02, 0x28, 0x0d, 0x52, 0x04, 0x5a,
	0x75, 0x48, 0x65, 0x12, 0x44, 0x0a, 0x0b, 0x57, 0x69, 0x6e, 0x55, 0x73, 0x65, 0x72, 0x49, 0x6e,
	0x66, 0x6f, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x22, 0x2e, 0x6e, 0x65, 0x74, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x42, 0x4a, 0x4c, 0x5f, 0x47, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x4f, 0x6e, 0x65, 0x55, 0x73, 0x65, 0x72, 0x57, 0x69, 0x6e, 0x52, 0x0b, 0x57, 0x69,
	0x6e, 0x55, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x22, 0x8d, 0x01, 0x0a, 0x17, 0x42, 0x4a,
	0x4c, 0x5f, 0x47, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x55, 0x73, 0x65, 0x72,
	0x4d, 0x6f, 0x6e, 0x65, 0x79, 0x12, 0x1c, 0x0a, 0x09, 0x5a, 0x68, 0x75, 0x61, 0x6e, 0x67, 0x57,
	0x69, 0x6e, 0x18, 0x01, 0x20, 0x02, 0x28, 0x03, 0x52, 0x09, 0x5a, 0x68, 0x75, 0x61, 0x6e, 0x67,
	0x57, 0x69, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x53, 0x65, 0x6c, 0x66, 0x57, 0x69, 0x6e, 0x18, 0x02,
	0x20, 0x02, 0x28, 0x03, 0x52, 0x07, 0x53, 0x65, 0x6c, 0x66, 0x57, 0x69, 0x6e, 0x12, 0x3a, 0x0a,
	0x0b, 0x57, 0x69, 0x6e, 0x55, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x18, 0x03, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x18, 0x2e, 0x6e, 0x65, 0x74, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x42, 0x4a,
	0x4c, 0x5f, 0x57, 0x69, 0x6e, 0x55, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x0b, 0x57, 0x69,
	0x6e, 0x55, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x22, 0x3e, 0x0a, 0x0e, 0x42, 0x4a, 0x4c,
	0x5f, 0x57, 0x69, 0x6e, 0x55, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x1a, 0x0a, 0x08, 0x55,
	0x73, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x02, 0x28, 0x09, 0x52, 0x08, 0x55,
	0x73, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x57, 0x69, 0x6e, 0x18, 0x02,
	0x20, 0x02, 0x28, 0x03, 0x52, 0x03, 0x57, 0x69, 0x6e, 0x22, 0x8d, 0x01, 0x0a, 0x09, 0x42, 0x4a,
	0x4c, 0x5f, 0x50, 0x6f, 0x6b, 0x65, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x43, 0x6f, 0x6c, 0x6f, 0x72,
	0x18, 0x01, 0x20, 0x02, 0x28, 0x05, 0x52, 0x05, 0x43, 0x6f, 0x6c, 0x6f, 0x72, 0x12, 0x16, 0x0a,
	0x06, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x02, 0x20, 0x02, 0x28, 0x05, 0x52, 0x06, 0x4e,
	0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x12, 0x1c, 0x0a, 0x09, 0x50,
	0x6c, 0x61, 0x69, 0x6e, 0x54, 0x65, 0x78, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09,
	0x50, 0x6c, 0x61, 0x69, 0x6e, 0x54, 0x65, 0x78, 0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x45, 0x6e, 0x63,
	0x6f, 0x64, 0x65, 0x54, 0x65, 0x78, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x45,
	0x6e, 0x63, 0x6f, 0x64, 0x65, 0x54, 0x65, 0x78, 0x74, 0x22, 0x40, 0x0a, 0x09, 0x42, 0x4a, 0x4c,
	0x5f, 0x43, 0x61, 0x72, 0x64, 0x73, 0x12, 0x33, 0x0a, 0x05, 0x43, 0x61, 0x72, 0x64, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x6e, 0x65, 0x74, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x42, 0x4a, 0x4c, 0x5f, 0x47, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x50,
	0x6f, 0x6b, 0x65, 0x72, 0x52, 0x05, 0x43, 0x61, 0x72, 0x64, 0x73, 0x22, 0x6c, 0x0a, 0x11, 0x42,
	0x4a, 0x4c, 0x5f, 0x47, 0x61, 0x6d, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x49, 0x6e, 0x66, 0x6f,
	0x12, 0x3d, 0x0a, 0x0a, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x50, 0x6f, 0x6b, 0x65, 0x18, 0x01,
	0x20, 0x02, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x6e, 0x65, 0x74, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x42, 0x4a, 0x4c, 0x5f, 0x47, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x50, 0x6f,
	0x6b, 0x65, 0x72, 0x52, 0x0a, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x50, 0x6f, 0x6b, 0x65, 0x12,
	0x18, 0x0a, 0x07, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x4e, 0x6f, 0x18, 0x02, 0x20, 0x02, 0x28, 0x05,
	0x52, 0x07, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x4e, 0x6f, 0x22, 0x69, 0x0a, 0x12, 0x42, 0x4a, 0x4c,
	0x5f, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x43, 0x61, 0x72, 0x64, 0x4c, 0x69, 0x73, 0x74, 0x12,
	0x39, 0x0a, 0x08, 0x43, 0x61, 0x72, 0x64, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x1d, 0x2e, 0x6e, 0x65, 0x74, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x42, 0x4a, 0x4c,
	0x5f, 0x47, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x50, 0x6f, 0x6b, 0x65, 0x72,
	0x52, 0x08, 0x43, 0x61, 0x72, 0x64, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x54, 0x61,
	0x62, 0x6c, 0x65, 0x4e, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x54, 0x61, 0x62,
	0x6c, 0x65, 0x4e, 0x6f, 0x22, 0x26, 0x0a, 0x12, 0x42, 0x4a, 0x4c, 0x5f, 0x53, 0x68, 0x61, 0x6e,
	0x67, 0x7a, 0x68, 0x75, 0x61, 0x6e, 0x67, 0x52, 0x65, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x72, 0x65,
	0x74, 0x18, 0x01, 0x20, 0x02, 0x28, 0x05, 0x52, 0x03, 0x72, 0x65, 0x74, 0x22, 0x37, 0x0a, 0x0f,
	0x42, 0x4a, 0x4c, 0x5f, 0x53, 0x68, 0x61, 0x6e, 0x67, 0x5a, 0x68, 0x75, 0x61, 0x6e, 0x67, 0x12,
	0x24, 0x0a, 0x0d, 0x49, 0x73, 0x53, 0x68, 0x61, 0x6e, 0x67, 0x5a, 0x68, 0x75, 0x61, 0x6e, 0x67,
	0x18, 0x01, 0x20, 0x02, 0x28, 0x08, 0x52, 0x0d, 0x49, 0x73, 0x53, 0x68, 0x61, 0x6e, 0x67, 0x5a,
	0x68, 0x75, 0x61, 0x6e, 0x67, 0x22, 0x96, 0x01, 0x0a, 0x0e, 0x42, 0x4a, 0x4c, 0x5f, 0x5a, 0x68,
	0x75, 0x61, 0x6e, 0x67, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x16, 0x0a, 0x06, 0x55, 0x73, 0x65, 0x72,
	0x49, 0x44, 0x18, 0x01, 0x20, 0x02, 0x28, 0x05, 0x52, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44,
	0x12, 0x1a, 0x0a, 0x08, 0x4c, 0x61, 0x73, 0x74, 0x54, 0x75, 0x72, 0x6e, 0x18, 0x02, 0x20, 0x02,
	0x28, 0x05, 0x52, 0x08, 0x4c, 0x61, 0x73, 0x74, 0x54, 0x75, 0x72, 0x6e, 0x12, 0x2e, 0x0a, 0x08,
	0x55, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x12,
	0x2e, 0x6e, 0x65, 0x74, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x47, 0x61, 0x6d, 0x65, 0x55, 0x73,
	0x65, 0x72, 0x52, 0x08, 0x55, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x20, 0x0a, 0x0b,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x0b, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x22, 0x40,
	0x0a, 0x0e, 0x42, 0x4a, 0x4c, 0x5f, 0x5a, 0x68, 0x75, 0x61, 0x6e, 0x67, 0x4c, 0x69, 0x73, 0x74,
	0x12, 0x2e, 0x0a, 0x08, 0x55, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x12, 0x2e, 0x6e, 0x65, 0x74, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x47, 0x61,
	0x6d, 0x65, 0x55, 0x73, 0x65, 0x72, 0x52, 0x08, 0x55, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f,
	0x22, 0x39, 0x0a, 0x0f, 0x42, 0x4a, 0x4c, 0x5f, 0x42, 0x65, 0x74, 0x43, 0x6c, 0x65, 0x61, 0x72,
	0x52, 0x65, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x4d, 0x6f, 0x6e, 0x65, 0x79, 0x18, 0x01, 0x20, 0x02,
	0x28, 0x03, 0x52, 0x05, 0x4d, 0x6f, 0x6e, 0x65, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x52, 0x65, 0x74,
	0x18, 0x02, 0x20, 0x02, 0x28, 0x05, 0x52, 0x03, 0x52, 0x65, 0x74, 0x22, 0x4b, 0x0a, 0x19, 0x42,
	0x4a, 0x4c, 0x5f, 0x47, 0x61, 0x6d, 0x65, 0x55, 0x73, 0x65, 0x72, 0x53, 0x63, 0x6f, 0x72, 0x65,
	0x52, 0x61, 0x6e, 0x6b, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x2e, 0x0a, 0x08, 0x55, 0x73, 0x65, 0x72,
	0x4c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x6e, 0x65, 0x74,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x47, 0x61, 0x6d, 0x65, 0x55, 0x73, 0x65, 0x72, 0x52, 0x08,
	0x55, 0x73, 0x65, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x22, 0xd1, 0x02, 0x0a, 0x0d, 0x42, 0x4a, 0x4c,
	0x5f, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x18, 0x0a, 0x07, 0x54, 0x61,
	0x62, 0x6c, 0x65, 0x4e, 0x6f, 0x18, 0x01, 0x20, 0x02, 0x28, 0x05, 0x52, 0x07, 0x54, 0x61, 0x62,
	0x6c, 0x65, 0x4e, 0x6f, 0x12, 0x16, 0x0a, 0x06, 0x53, 0x68, 0x6f, 0x65, 0x4e, 0x6f, 0x18, 0x02,
	0x20, 0x02, 0x28, 0x05, 0x52, 0x06, 0x53, 0x68, 0x6f, 0x65, 0x4e, 0x6f, 0x12, 0x16, 0x0a, 0x06,
	0x47, 0x61, 0x6d, 0x65, 0x4e, 0x6f, 0x18, 0x03, 0x20, 0x02, 0x28, 0x05, 0x52, 0x06, 0x47, 0x61,
	0x6d, 0x65, 0x4e, 0x6f, 0x12, 0x26, 0x0a, 0x0e, 0x46, 0x69, 0x72, 0x73, 0x74, 0x43, 0x61, 0x72,
	0x64, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x04, 0x20, 0x02, 0x28, 0x05, 0x52, 0x0e, 0x46, 0x69,
	0x72, 0x73, 0x74, 0x43, 0x61, 0x72, 0x64, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x12, 0x1a, 0x0a, 0x08,
	0x4d, 0x69, 0x6e, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x05, 0x20, 0x02, 0x28, 0x05, 0x52, 0x08,
	0x4d, 0x69, 0x6e, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x4d, 0x61, 0x78, 0x4c,
	0x69, 0x6d, 0x69, 0x74, 0x18, 0x06, 0x20, 0x02, 0x28, 0x05, 0x52, 0x08, 0x4d, 0x61, 0x78, 0x4c,
	0x69, 0x6d, 0x69, 0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x4c, 0x69, 0x6d,
	0x69, 0x74, 0x18, 0x07, 0x20, 0x02, 0x28, 0x05, 0x52, 0x0a, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x4c,
	0x69, 0x6d, 0x69, 0x74, 0x12, 0x20, 0x0a, 0x0b, 0x42, 0x61, 0x6e, 0x6b, 0x65, 0x72, 0x4c, 0x69,
	0x6d, 0x69, 0x74, 0x18, 0x08, 0x20, 0x02, 0x28, 0x05, 0x52, 0x0b, 0x42, 0x61, 0x6e, 0x6b, 0x65,
	0x72, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x50, 0x61, 0x69, 0x72, 0x4c, 0x69,
	0x6d, 0x69, 0x74, 0x18, 0x09, 0x20, 0x02, 0x28, 0x05, 0x52, 0x09, 0x50, 0x61, 0x69, 0x72, 0x4c,
	0x69, 0x6d, 0x69, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x54, 0x69, 0x65, 0x4c, 0x69, 0x6d, 0x69, 0x74,
	0x18, 0x0a, 0x20, 0x02, 0x28, 0x05, 0x52, 0x08, 0x54, 0x69, 0x65, 0x4c, 0x69, 0x6d, 0x69, 0x74,
	0x12, 0x1a, 0x0a, 0x08, 0x47, 0x61, 0x6d, 0x65, 0x4c, 0x6d, 0x69, 0x74, 0x18, 0x0b, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x08, 0x47, 0x61, 0x6d, 0x65, 0x4c, 0x6d, 0x69, 0x74, 0x42, 0x0c, 0x5a, 0x0a,
	0x2e, 0x2f, 0x6e, 0x65, 0x74, 0x70, 0x72, 0x6f, 0x74, 0x6f,
}

var (
	file_GameMsg_BJL_proto_rawDescOnce sync.Once
	file_GameMsg_BJL_proto_rawDescData = file_GameMsg_BJL_proto_rawDesc
)

func file_GameMsg_BJL_proto_rawDescGZIP() []byte {
	file_GameMsg_BJL_proto_rawDescOnce.Do(func() {
		file_GameMsg_BJL_proto_rawDescData = protoimpl.X.CompressGZIP(file_GameMsg_BJL_proto_rawDescData)
	})
	return file_GameMsg_BJL_proto_rawDescData
}

var file_GameMsg_BJL_proto_msgTypes = make([]protoimpl.MessageInfo, 24)
var file_GameMsg_BJL_proto_goTypes = []interface{}{
	(*BJL_Setting)(nil),               // 0: netproto.BJL_Setting
	(*BJL_Sate)(nil),                  // 1: netproto.BJL_Sate
	(*BJL_UserBetInfo)(nil),           // 2: netproto.BJL_UserBetInfo
	(*BJL_BroadCastBetArr)(nil),       // 3: netproto.BJL_BroadCastBetArr
	(*BJL_BroadCastBet)(nil),          // 4: netproto.BJL_BroadCastBet
	(*BJL_BetArr)(nil),                // 5: netproto.BJL_BetArr
	(*BJL_Bet)(nil),                   // 6: netproto.BJL_Bet
	(*BJL_BetRet)(nil),                // 7: netproto.BJL_BetRet
	(*BJL_GameResultPoker)(nil),       // 8: netproto.BJL_GameResultPoker
	(*BJL_GameResultOneUserWin)(nil),  // 9: netproto.BJL_GameResultOneUserWin
	(*BJL_GameResultTOPNWin)(nil),     // 10: netproto.BJL_GameResultTOPNWin
	(*BJL_GameResultUserMoney)(nil),   // 11: netproto.BJL_GameResultUserMoney
	(*BJL_WinUerInfo)(nil),            // 12: netproto.BJL_WinUerInfo
	(*BJL_Poker)(nil),                 // 13: netproto.BJL_Poker
	(*BJL_Cards)(nil),                 // 14: netproto.BJL_Cards
	(*BJL_GamResultInfo)(nil),         // 15: netproto.BJL_GamResultInfo
	(*BJL_ResultCardList)(nil),        // 16: netproto.BJL_ResultCardList
	(*BJL_ShangzhuangRet)(nil),        // 17: netproto.BJL_ShangzhuangRet
	(*BJL_ShangZhuang)(nil),           // 18: netproto.BJL_ShangZhuang
	(*BJL_ZhuangInfo)(nil),            // 19: netproto.BJL_ZhuangInfo
	(*BJL_ZhuangList)(nil),            // 20: netproto.BJL_ZhuangList
	(*BJL_BetClearRet)(nil),           // 21: netproto.BJL_BetClearRet
	(*BJL_GameUserScoreRankList)(nil), // 22: netproto.BJL_GameUserScoreRankList
	(*BJL_TableInfo)(nil),             // 23: netproto.BJL_TableInfo
	(*GameUser)(nil),                  // 24: netproto.GameUser
}
var file_GameMsg_BJL_proto_depIdxs = []int32{
	4,  // 0: netproto.BJL_UserBetInfo.BetInfo:type_name -> netproto.BJL_BroadCastBet
	4,  // 1: netproto.BJL_BroadCastBetArr.BroadCastBetArr:type_name -> netproto.BJL_BroadCastBet
	6,  // 2: netproto.BJL_BroadCastBetArr.BetArrSelf:type_name -> netproto.BJL_Bet
	6,  // 3: netproto.BJL_BetArr.BetArr:type_name -> netproto.BJL_Bet
	6,  // 4: netproto.BJL_BetRet.BetArr:type_name -> netproto.BJL_Bet
	6,  // 5: netproto.BJL_BetRet.TotalBetArr:type_name -> netproto.BJL_Bet
	13, // 6: netproto.BJL_GameResultPoker.ZhuangPoker:type_name -> netproto.BJL_Poker
	13, // 7: netproto.BJL_GameResultPoker.XianPoker:type_name -> netproto.BJL_Poker
	9,  // 8: netproto.BJL_GameResultTOPNWin.WinUserInfo:type_name -> netproto.BJL_GameResultOneUserWin
	12, // 9: netproto.BJL_GameResultUserMoney.WinUserInfo:type_name -> netproto.BJL_WinUerInfo
	8,  // 10: netproto.BJL_Cards.Cards:type_name -> netproto.BJL_GameResultPoker
	8,  // 11: netproto.BJL_GamResultInfo.ResultPoke:type_name -> netproto.BJL_GameResultPoker
	8,  // 12: netproto.BJL_ResultCardList.CardList:type_name -> netproto.BJL_GameResultPoker
	24, // 13: netproto.BJL_ZhuangInfo.UserInfo:type_name -> netproto.GameUser
	24, // 14: netproto.BJL_ZhuangList.UserInfo:type_name -> netproto.GameUser
	24, // 15: netproto.BJL_GameUserScoreRankList.UserList:type_name -> netproto.GameUser
	16, // [16:16] is the sub-list for method output_type
	16, // [16:16] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_GameMsg_BJL_proto_init() }
func file_GameMsg_BJL_proto_init() {
	if File_GameMsg_BJL_proto != nil {
		return
	}
	file_GameMsg_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_GameMsg_BJL_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BJL_Setting); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_GameMsg_BJL_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BJL_Sate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_GameMsg_BJL_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BJL_UserBetInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_GameMsg_BJL_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BJL_BroadCastBetArr); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_GameMsg_BJL_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BJL_BroadCastBet); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_GameMsg_BJL_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BJL_BetArr); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_GameMsg_BJL_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BJL_Bet); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_GameMsg_BJL_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BJL_BetRet); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_GameMsg_BJL_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BJL_GameResultPoker); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_GameMsg_BJL_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BJL_GameResultOneUserWin); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_GameMsg_BJL_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BJL_GameResultTOPNWin); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_GameMsg_BJL_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BJL_GameResultUserMoney); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_GameMsg_BJL_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BJL_WinUerInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_GameMsg_BJL_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BJL_Poker); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_GameMsg_BJL_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BJL_Cards); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_GameMsg_BJL_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BJL_GamResultInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_GameMsg_BJL_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BJL_ResultCardList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_GameMsg_BJL_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BJL_ShangzhuangRet); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_GameMsg_BJL_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BJL_ShangZhuang); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_GameMsg_BJL_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BJL_ZhuangInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_GameMsg_BJL_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BJL_ZhuangList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_GameMsg_BJL_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BJL_BetClearRet); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_GameMsg_BJL_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BJL_GameUserScoreRankList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_GameMsg_BJL_proto_msgTypes[23].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BJL_TableInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_GameMsg_BJL_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   24,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_GameMsg_BJL_proto_goTypes,
		DependencyIndexes: file_GameMsg_BJL_proto_depIdxs,
		MessageInfos:      file_GameMsg_BJL_proto_msgTypes,
	}.Build()
	File_GameMsg_BJL_proto = out.File
	file_GameMsg_BJL_proto_rawDesc = nil
	file_GameMsg_BJL_proto_goTypes = nil
	file_GameMsg_BJL_proto_depIdxs = nil
}
