// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        (unknown)
// source: NotifyServer.proto

package netproto

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type NotifyServerClassID int32

const (
	NotifyServerClassID_ServerRegID             NotifyServerClassID = 1
	NotifyServerClassID_AnnID                   NotifyServerClassID = 2
	NotifyServerClassID_AttrChangeID            NotifyServerClassID = 3
	NotifyServerClassID_ServerStopID            NotifyServerClassID = 4
	NotifyServerClassID_RefreshVersionID        NotifyServerClassID = 5
	NotifyServerClassID_ServerStopWhiteIPListID NotifyServerClassID = 6
	NotifyServerClassID_RefreshGameVersionID    NotifyServerClassID = 7
	NotifyServerClassID_GameStatusChangeID      NotifyServerClassID = 8
	NotifyServerClassID_GameLockTraceChangeID   NotifyServerClassID = 9
	NotifyServerClassID_VersionID               NotifyServerClassID = 10
)

// Enum value maps for NotifyServerClassID.
var (
	NotifyServerClassID_name = map[int32]string{
		1:  "ServerRegID",
		2:  "AnnID",
		3:  "AttrChangeID",
		4:  "ServerStopID",
		5:  "RefreshVersionID",
		6:  "ServerStopWhiteIPListID",
		7:  "RefreshGameVersionID",
		8:  "GameStatusChangeID",
		9:  "GameLockTraceChangeID",
		10: "VersionID",
	}
	NotifyServerClassID_value = map[string]int32{
		"ServerRegID":             1,
		"AnnID":                   2,
		"AttrChangeID":            3,
		"ServerStopID":            4,
		"RefreshVersionID":        5,
		"ServerStopWhiteIPListID": 6,
		"RefreshGameVersionID":    7,
		"GameStatusChangeID":      8,
		"GameLockTraceChangeID":   9,
		"VersionID":               10,
	}
)

func (x NotifyServerClassID) Enum() *NotifyServerClassID {
	p := new(NotifyServerClassID)
	*p = x
	return p
}

func (x NotifyServerClassID) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NotifyServerClassID) Descriptor() protoreflect.EnumDescriptor {
	return file_NotifyServer_proto_enumTypes[0].Descriptor()
}

func (NotifyServerClassID) Type() protoreflect.EnumType {
	return &file_NotifyServer_proto_enumTypes[0]
}

func (x NotifyServerClassID) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *NotifyServerClassID) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = NotifyServerClassID(num)
	return nil
}

// Deprecated: Use NotifyServerClassID.Descriptor instead.
func (NotifyServerClassID) EnumDescriptor() ([]byte, []int) {
	return file_NotifyServer_proto_rawDescGZIP(), []int{0}
}

var File_NotifyServer_proto protoreflect.FileDescriptor

var file_NotifyServer_proto_rawDesc = []byte{
	0x0a, 0x12, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x6e, 0x65, 0x74, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2a, 0xe4,
	0x01, 0x0a, 0x13, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x43,
	0x6c, 0x61, 0x73, 0x73, 0x49, 0x44, 0x12, 0x0f, 0x0a, 0x0b, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72,
	0x52, 0x65, 0x67, 0x49, 0x44, 0x10, 0x01, 0x12, 0x09, 0x0a, 0x05, 0x41, 0x6e, 0x6e, 0x49, 0x44,
	0x10, 0x02, 0x12, 0x10, 0x0a, 0x0c, 0x41, 0x74, 0x74, 0x72, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65,
	0x49, 0x44, 0x10, 0x03, 0x12, 0x10, 0x0a, 0x0c, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x53, 0x74,
	0x6f, 0x70, 0x49, 0x44, 0x10, 0x04, 0x12, 0x14, 0x0a, 0x10, 0x52, 0x65, 0x66, 0x72, 0x65, 0x73,
	0x68, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x44, 0x10, 0x05, 0x12, 0x1b, 0x0a, 0x17,
	0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x53, 0x74, 0x6f, 0x70, 0x57, 0x68, 0x69, 0x74, 0x65, 0x49,
	0x50, 0x4c, 0x69, 0x73, 0x74, 0x49, 0x44, 0x10, 0x06, 0x12, 0x18, 0x0a, 0x14, 0x52, 0x65, 0x66,
	0x72, 0x65, 0x73, 0x68, 0x47, 0x61, 0x6d, 0x65, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x49,
	0x44, 0x10, 0x07, 0x12, 0x16, 0x0a, 0x12, 0x47, 0x61, 0x6d, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x49, 0x44, 0x10, 0x08, 0x12, 0x19, 0x0a, 0x15, 0x47,
	0x61, 0x6d, 0x65, 0x4c, 0x6f, 0x63, 0x6b, 0x54, 0x72, 0x61, 0x63, 0x65, 0x43, 0x68, 0x61, 0x6e,
	0x67, 0x65, 0x49, 0x44, 0x10, 0x09, 0x12, 0x0d, 0x0a, 0x09, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f,
	0x6e, 0x49, 0x44, 0x10, 0x0a,
}

var (
	file_NotifyServer_proto_rawDescOnce sync.Once
	file_NotifyServer_proto_rawDescData = file_NotifyServer_proto_rawDesc
)

func file_NotifyServer_proto_rawDescGZIP() []byte {
	file_NotifyServer_proto_rawDescOnce.Do(func() {
		file_NotifyServer_proto_rawDescData = protoimpl.X.CompressGZIP(file_NotifyServer_proto_rawDescData)
	})
	return file_NotifyServer_proto_rawDescData
}

var file_NotifyServer_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_NotifyServer_proto_goTypes = []interface{}{
	(NotifyServerClassID)(0), // 0: netproto.NotifyServerClassID
}
var file_NotifyServer_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_NotifyServer_proto_init() }
func file_NotifyServer_proto_init() {
	if File_NotifyServer_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_NotifyServer_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_NotifyServer_proto_goTypes,
		DependencyIndexes: file_NotifyServer_proto_depIdxs,
		EnumInfos:         file_NotifyServer_proto_enumTypes,
	}.Build()
	File_NotifyServer_proto = out.File
	file_NotifyServer_proto_rawDesc = nil
	file_NotifyServer_proto_goTypes = nil
	file_NotifyServer_proto_depIdxs = nil
}
