// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.19.1
// source: NotifyServerMsg.proto

package netproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NotifyServerRegInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ServerID   *int32 `protobuf:"varint,1,req,name=ServerID" json:"ServerID,omitempty"`     //服務器ID
	GameID     *int32 `protobuf:"varint,2,opt,name=GameID" json:"GameID,omitempty"`         //遊戲ID
	ServerType *int32 `protobuf:"varint,3,req,name=ServerType" json:"ServerType,omitempty"` //服務器類型
	LianyunID  *int32 `protobuf:"varint,4,opt,name=LianyunID" json:"LianyunID,omitempty"`   //聯運ID
}

func (x *NotifyServerRegInfo) Reset() {
	*x = NotifyServerRegInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_NotifyServerMsg_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NotifyServerRegInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyServerRegInfo) ProtoMessage() {}

func (x *NotifyServerRegInfo) ProtoReflect() protoreflect.Message {
	mi := &file_NotifyServerMsg_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyServerRegInfo.ProtoReflect.Descriptor instead.
func (*NotifyServerRegInfo) Descriptor() ([]byte, []int) {
	return file_NotifyServerMsg_proto_rawDescGZIP(), []int{0}
}

func (x *NotifyServerRegInfo) GetServerID() int32 {
	if x != nil && x.ServerID != nil {
		return *x.ServerID
	}
	return 0
}

func (x *NotifyServerRegInfo) GetGameID() int32 {
	if x != nil && x.GameID != nil {
		return *x.GameID
	}
	return 0
}

func (x *NotifyServerRegInfo) GetServerType() int32 {
	if x != nil && x.ServerType != nil {
		return *x.ServerType
	}
	return 0
}

func (x *NotifyServerRegInfo) GetLianyunID() int32 {
	if x != nil && x.LianyunID != nil {
		return *x.LianyunID
	}
	return 0
}

type AnnInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID         *int32       `protobuf:"varint,1,req,name=ID" json:"ID,omitempty"`
	PlatformID *int32       `protobuf:"varint,2,req,name=PlatformID" json:"PlatformID,omitempty"`
	MsgContent *string      `protobuf:"bytes,3,req,name=MsgContent" json:"MsgContent,omitempty"`
	Type       *int32       `protobuf:"varint,4,opt,name=Type" json:"Type,omitempty"`                                   //消息類型 0:遊戲數據-機器人玩家, 10:遊戲數據-普通玩家, 20:活動數據 30:後臺設定
	CodeLG     *int32       `protobuf:"varint,5,opt,name=CodeLG" json:"CodeLG,omitempty"`                               //語言代碼,
	ParamLG    *string      `protobuf:"bytes,6,opt,name=ParamLG" json:"ParamLG,omitempty"`                              //語言代碼對應的參數，多個參數以 | 分割，如：11|aa|abc123
	Range      *AnnRange    `protobuf:"varint,7,req,name=Range,enum=netproto.AnnRange" json:"Range,omitempty"`          // 使用範圍
	Priority   *AnnPriority `protobuf:"varint,8,req,name=Priority,enum=netproto.AnnPriority" json:"Priority,omitempty"` // 優先度
}

func (x *AnnInfo) Reset() {
	*x = AnnInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_NotifyServerMsg_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AnnInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnnInfo) ProtoMessage() {}

func (x *AnnInfo) ProtoReflect() protoreflect.Message {
	mi := &file_NotifyServerMsg_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnnInfo.ProtoReflect.Descriptor instead.
func (*AnnInfo) Descriptor() ([]byte, []int) {
	return file_NotifyServerMsg_proto_rawDescGZIP(), []int{1}
}

func (x *AnnInfo) GetID() int32 {
	if x != nil && x.ID != nil {
		return *x.ID
	}
	return 0
}

func (x *AnnInfo) GetPlatformID() int32 {
	if x != nil && x.PlatformID != nil {
		return *x.PlatformID
	}
	return 0
}

func (x *AnnInfo) GetMsgContent() string {
	if x != nil && x.MsgContent != nil {
		return *x.MsgContent
	}
	return ""
}

func (x *AnnInfo) GetType() int32 {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return 0
}

func (x *AnnInfo) GetCodeLG() int32 {
	if x != nil && x.CodeLG != nil {
		return *x.CodeLG
	}
	return 0
}

func (x *AnnInfo) GetParamLG() string {
	if x != nil && x.ParamLG != nil {
		return *x.ParamLG
	}
	return ""
}

func (x *AnnInfo) GetRange() AnnRange {
	if x != nil && x.Range != nil {
		return *x.Range
	}
	return AnnRange_AnnRange_All
}

func (x *AnnInfo) GetPriority() AnnPriority {
	if x != nil && x.Priority != nil {
		return *x.Priority
	}
	return AnnPriority_AnnPriority_Low
}

type AnnList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ann []*AnnInfo `protobuf:"bytes,1,rep,name=Ann" json:"Ann,omitempty"`
}

func (x *AnnList) Reset() {
	*x = AnnList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_NotifyServerMsg_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AnnList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnnList) ProtoMessage() {}

func (x *AnnList) ProtoReflect() protoreflect.Message {
	mi := &file_NotifyServerMsg_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnnList.ProtoReflect.Descriptor instead.
func (*AnnList) Descriptor() ([]byte, []int) {
	return file_NotifyServerMsg_proto_rawDescGZIP(), []int{2}
}

func (x *AnnList) GetAnn() []*AnnInfo {
	if x != nil {
		return x.Ann
	}
	return nil
}

type AttrChange struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserID *int32  `protobuf:"varint,1,req,name=UserID" json:"UserID,omitempty"` //用戶ID
	TypeID *int32  `protobuf:"varint,2,req,name=TypeID" json:"TypeID,omitempty"` //屬性類型 0 金幣變化 1 新郵件 2充值到賬 3充值金額配置變化 4充值顯示兌換按鈕 5更新玩家信息(銀行數據等)
	Param  *int64  `protobuf:"varint,3,opt,name=Param" json:"Param,omitempty"`   //當類型為0，2時為金幣變化數量,其它時無用
	SParam *string `protobuf:"bytes,4,opt,name=SParam" json:"SParam,omitempty"`  //當類型為3時，由平臺號與配置組成 1_xxx 1為平臺ID,xxx為充值金額配置信息
}

func (x *AttrChange) Reset() {
	*x = AttrChange{}
	if protoimpl.UnsafeEnabled {
		mi := &file_NotifyServerMsg_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AttrChange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttrChange) ProtoMessage() {}

func (x *AttrChange) ProtoReflect() protoreflect.Message {
	mi := &file_NotifyServerMsg_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttrChange.ProtoReflect.Descriptor instead.
func (*AttrChange) Descriptor() ([]byte, []int) {
	return file_NotifyServerMsg_proto_rawDescGZIP(), []int{3}
}

func (x *AttrChange) GetUserID() int32 {
	if x != nil && x.UserID != nil {
		return *x.UserID
	}
	return 0
}

func (x *AttrChange) GetTypeID() int32 {
	if x != nil && x.TypeID != nil {
		return *x.TypeID
	}
	return 0
}

func (x *AttrChange) GetParam() int64 {
	if x != nil && x.Param != nil {
		return *x.Param
	}
	return 0
}

func (x *AttrChange) GetSParam() string {
	if x != nil && x.SParam != nil {
		return *x.SParam
	}
	return ""
}

type AttrChangeList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Attrs []*AttrChange `protobuf:"bytes,1,rep,name=Attrs" json:"Attrs,omitempty"`
}

func (x *AttrChangeList) Reset() {
	*x = AttrChangeList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_NotifyServerMsg_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AttrChangeList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttrChangeList) ProtoMessage() {}

func (x *AttrChangeList) ProtoReflect() protoreflect.Message {
	mi := &file_NotifyServerMsg_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttrChangeList.ProtoReflect.Descriptor instead.
func (*AttrChangeList) Descriptor() ([]byte, []int) {
	return file_NotifyServerMsg_proto_rawDescGZIP(), []int{4}
}

func (x *AttrChangeList) GetAttrs() []*AttrChange {
	if x != nil {
		return x.Attrs
	}
	return nil
}

type ServerStop struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type      *int32  `protobuf:"varint,1,req,name=Type" json:"Type,omitempty"`
	Status    *int32  `protobuf:"varint,2,req,name=Status" json:"Status,omitempty"`
	GameID    *int32  `protobuf:"varint,3,opt,name=GameID" json:"GameID,omitempty"`
	ServerID  *int32  `protobuf:"varint,4,opt,name=ServerID" json:"ServerID,omitempty"`
	Message   *string `protobuf:"bytes,5,req,name=Message" json:"Message,omitempty"`
	LianyunID *int32  `protobuf:"varint,6,opt,name=LianyunID" json:"LianyunID,omitempty"` //聯運ID
}

func (x *ServerStop) Reset() {
	*x = ServerStop{}
	if protoimpl.UnsafeEnabled {
		mi := &file_NotifyServerMsg_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServerStop) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerStop) ProtoMessage() {}

func (x *ServerStop) ProtoReflect() protoreflect.Message {
	mi := &file_NotifyServerMsg_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerStop.ProtoReflect.Descriptor instead.
func (*ServerStop) Descriptor() ([]byte, []int) {
	return file_NotifyServerMsg_proto_rawDescGZIP(), []int{5}
}

func (x *ServerStop) GetType() int32 {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return 0
}

func (x *ServerStop) GetStatus() int32 {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return 0
}

func (x *ServerStop) GetGameID() int32 {
	if x != nil && x.GameID != nil {
		return *x.GameID
	}
	return 0
}

func (x *ServerStop) GetServerID() int32 {
	if x != nil && x.ServerID != nil {
		return *x.ServerID
	}
	return 0
}

func (x *ServerStop) GetMessage() string {
	if x != nil && x.Message != nil {
		return *x.Message
	}
	return ""
}

func (x *ServerStop) GetLianyunID() int32 {
	if x != nil && x.LianyunID != nil {
		return *x.LianyunID
	}
	return 0
}

type ServerStopWhiteIPList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IP []string `protobuf:"bytes,1,rep,name=IP" json:"IP,omitempty"`
}

func (x *ServerStopWhiteIPList) Reset() {
	*x = ServerStopWhiteIPList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_NotifyServerMsg_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServerStopWhiteIPList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerStopWhiteIPList) ProtoMessage() {}

func (x *ServerStopWhiteIPList) ProtoReflect() protoreflect.Message {
	mi := &file_NotifyServerMsg_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerStopWhiteIPList.ProtoReflect.Descriptor instead.
func (*ServerStopWhiteIPList) Descriptor() ([]byte, []int) {
	return file_NotifyServerMsg_proto_rawDescGZIP(), []int{6}
}

func (x *ServerStopWhiteIPList) GetIP() []string {
	if x != nil {
		return x.IP
	}
	return nil
}

type SMSVCode struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CodeID      *int32  `protobuf:"varint,1,opt,name=CodeID" json:"CodeID,omitempty"`           //SMS通知ID，僅標示數據庫中的唯一id
	Tel         *string `protobuf:"bytes,2,opt,name=Tel" json:"Tel,omitempty"`                  //手機號
	VCode       *string `protobuf:"bytes,3,opt,name=VCode" json:"VCode,omitempty"`              //驗證碼
	PlatformID  *int32  `protobuf:"varint,4,opt,name=PlatformID" json:"PlatformID,omitempty"`   //平臺ID
	CountryCode *int32  `protobuf:"varint,5,opt,name=CountryCode" json:"CountryCode,omitempty"` //國際代碼
}

func (x *SMSVCode) Reset() {
	*x = SMSVCode{}
	if protoimpl.UnsafeEnabled {
		mi := &file_NotifyServerMsg_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SMSVCode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SMSVCode) ProtoMessage() {}

func (x *SMSVCode) ProtoReflect() protoreflect.Message {
	mi := &file_NotifyServerMsg_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SMSVCode.ProtoReflect.Descriptor instead.
func (*SMSVCode) Descriptor() ([]byte, []int) {
	return file_NotifyServerMsg_proto_rawDescGZIP(), []int{7}
}

func (x *SMSVCode) GetCodeID() int32 {
	if x != nil && x.CodeID != nil {
		return *x.CodeID
	}
	return 0
}

func (x *SMSVCode) GetTel() string {
	if x != nil && x.Tel != nil {
		return *x.Tel
	}
	return ""
}

func (x *SMSVCode) GetVCode() string {
	if x != nil && x.VCode != nil {
		return *x.VCode
	}
	return ""
}

func (x *SMSVCode) GetPlatformID() int32 {
	if x != nil && x.PlatformID != nil {
		return *x.PlatformID
	}
	return 0
}

func (x *SMSVCode) GetCountryCode() int32 {
	if x != nil && x.CountryCode != nil {
		return *x.CountryCode
	}
	return 0
}

type SMSVCodeList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Attrs []*SMSVCode `protobuf:"bytes,1,rep,name=Attrs" json:"Attrs,omitempty"`
}

func (x *SMSVCodeList) Reset() {
	*x = SMSVCodeList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_NotifyServerMsg_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SMSVCodeList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SMSVCodeList) ProtoMessage() {}

func (x *SMSVCodeList) ProtoReflect() protoreflect.Message {
	mi := &file_NotifyServerMsg_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SMSVCodeList.ProtoReflect.Descriptor instead.
func (*SMSVCodeList) Descriptor() ([]byte, []int) {
	return file_NotifyServerMsg_proto_rawDescGZIP(), []int{8}
}

func (x *SMSVCodeList) GetAttrs() []*SMSVCode {
	if x != nil {
		return x.Attrs
	}
	return nil
}

type NotifyGameStatus struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ServerID     *int32 `protobuf:"varint,1,req,name=ServerID" json:"ServerID,omitempty"`         //服務器ID
	GameID       *int32 `protobuf:"varint,2,opt,name=GameID" json:"GameID,omitempty"`             //遊戲ID
	ServerStatus *int32 `protobuf:"varint,3,opt,name=ServerStatus" json:"ServerStatus,omitempty"` //遊戲服狀態
	LianyunID    *int32 `protobuf:"varint,4,opt,name=LianyunID" json:"LianyunID,omitempty"`       //聯運ID
}

func (x *NotifyGameStatus) Reset() {
	*x = NotifyGameStatus{}
	if protoimpl.UnsafeEnabled {
		mi := &file_NotifyServerMsg_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NotifyGameStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyGameStatus) ProtoMessage() {}

func (x *NotifyGameStatus) ProtoReflect() protoreflect.Message {
	mi := &file_NotifyServerMsg_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyGameStatus.ProtoReflect.Descriptor instead.
func (*NotifyGameStatus) Descriptor() ([]byte, []int) {
	return file_NotifyServerMsg_proto_rawDescGZIP(), []int{9}
}

func (x *NotifyGameStatus) GetServerID() int32 {
	if x != nil && x.ServerID != nil {
		return *x.ServerID
	}
	return 0
}

func (x *NotifyGameStatus) GetGameID() int32 {
	if x != nil && x.GameID != nil {
		return *x.GameID
	}
	return 0
}

func (x *NotifyGameStatus) GetServerStatus() int32 {
	if x != nil && x.ServerStatus != nil {
		return *x.ServerStatus
	}
	return 0
}

func (x *NotifyGameStatus) GetLianyunID() int32 {
	if x != nil && x.LianyunID != nil {
		return *x.LianyunID
	}
	return 0
}

type GameLockTraceChange struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SuperUserID *int32 `protobuf:"varint,1,req,name=SuperUserID" json:"SuperUserID,omitempty"`
	TraceUserID *int32 `protobuf:"varint,2,req,name=TraceUserID" json:"TraceUserID,omitempty"`
}

func (x *GameLockTraceChange) Reset() {
	*x = GameLockTraceChange{}
	if protoimpl.UnsafeEnabled {
		mi := &file_NotifyServerMsg_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GameLockTraceChange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameLockTraceChange) ProtoMessage() {}

func (x *GameLockTraceChange) ProtoReflect() protoreflect.Message {
	mi := &file_NotifyServerMsg_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameLockTraceChange.ProtoReflect.Descriptor instead.
func (*GameLockTraceChange) Descriptor() ([]byte, []int) {
	return file_NotifyServerMsg_proto_rawDescGZIP(), []int{10}
}

func (x *GameLockTraceChange) GetSuperUserID() int32 {
	if x != nil && x.SuperUserID != nil {
		return *x.SuperUserID
	}
	return 0
}

func (x *GameLockTraceChange) GetTraceUserID() int32 {
	if x != nil && x.TraceUserID != nil {
		return *x.TraceUserID
	}
	return 0
}

type GameLockTraceChangeList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TraceChange []*GameLockTraceChange `protobuf:"bytes,1,rep,name=TraceChange" json:"TraceChange,omitempty"`
}

func (x *GameLockTraceChangeList) Reset() {
	*x = GameLockTraceChangeList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_NotifyServerMsg_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GameLockTraceChangeList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameLockTraceChangeList) ProtoMessage() {}

func (x *GameLockTraceChangeList) ProtoReflect() protoreflect.Message {
	mi := &file_NotifyServerMsg_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameLockTraceChangeList.ProtoReflect.Descriptor instead.
func (*GameLockTraceChangeList) Descriptor() ([]byte, []int) {
	return file_NotifyServerMsg_proto_rawDescGZIP(), []int{11}
}

func (x *GameLockTraceChangeList) GetTraceChange() []*GameLockTraceChange {
	if x != nil {
		return x.TraceChange
	}
	return nil
}

type VersionInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID       *int32  `protobuf:"varint,1,req,name=ID" json:"ID,omitempty"`            //ID
	BunldID  *string `protobuf:"bytes,2,req,name=BunldID" json:"BunldID,omitempty"`   //包ID
	Ver      *string `protobuf:"bytes,3,req,name=Ver" json:"Ver,omitempty"`           //資源版本
	Path     *string `protobuf:"bytes,4,req,name=Path" json:"Path,omitempty"`         //全路徑
	Ver1     *string `protobuf:"bytes,5,req,name=Ver1" json:"Ver1,omitempty"`         //資源版本1
	Platform *string `protobuf:"bytes,6,opt,name=Platform" json:"Platform,omitempty"` //平臺
	Channel  *string `protobuf:"bytes,7,opt,name=Channel" json:"Channel,omitempty"`   //支援更新的通路
	SkinVer  *string `protobuf:"bytes,8,req,name=SkinVer" json:"SkinVer,omitempty"`   //皮版本
	LimitIP  *string `protobuf:"bytes,9,opt,name=LimitIP" json:"LimitIP,omitempty"`   //限製IP
}

func (x *VersionInfo) Reset() {
	*x = VersionInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_NotifyServerMsg_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VersionInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VersionInfo) ProtoMessage() {}

func (x *VersionInfo) ProtoReflect() protoreflect.Message {
	mi := &file_NotifyServerMsg_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VersionInfo.ProtoReflect.Descriptor instead.
func (*VersionInfo) Descriptor() ([]byte, []int) {
	return file_NotifyServerMsg_proto_rawDescGZIP(), []int{12}
}

func (x *VersionInfo) GetID() int32 {
	if x != nil && x.ID != nil {
		return *x.ID
	}
	return 0
}

func (x *VersionInfo) GetBunldID() string {
	if x != nil && x.BunldID != nil {
		return *x.BunldID
	}
	return ""
}

func (x *VersionInfo) GetVer() string {
	if x != nil && x.Ver != nil {
		return *x.Ver
	}
	return ""
}

func (x *VersionInfo) GetPath() string {
	if x != nil && x.Path != nil {
		return *x.Path
	}
	return ""
}

func (x *VersionInfo) GetVer1() string {
	if x != nil && x.Ver1 != nil {
		return *x.Ver1
	}
	return ""
}

func (x *VersionInfo) GetPlatform() string {
	if x != nil && x.Platform != nil {
		return *x.Platform
	}
	return ""
}

func (x *VersionInfo) GetChannel() string {
	if x != nil && x.Channel != nil {
		return *x.Channel
	}
	return ""
}

func (x *VersionInfo) GetSkinVer() string {
	if x != nil && x.SkinVer != nil {
		return *x.SkinVer
	}
	return ""
}

func (x *VersionInfo) GetLimitIP() string {
	if x != nil && x.LimitIP != nil {
		return *x.LimitIP
	}
	return ""
}

type VersionList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ver []*VersionInfo `protobuf:"bytes,1,rep,name=Ver" json:"Ver,omitempty"`
}

func (x *VersionList) Reset() {
	*x = VersionList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_NotifyServerMsg_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VersionList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VersionList) ProtoMessage() {}

func (x *VersionList) ProtoReflect() protoreflect.Message {
	mi := &file_NotifyServerMsg_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VersionList.ProtoReflect.Descriptor instead.
func (*VersionList) Descriptor() ([]byte, []int) {
	return file_NotifyServerMsg_proto_rawDescGZIP(), []int{13}
}

func (x *VersionList) GetVer() []*VersionInfo {
	if x != nil {
		return x.Ver
	}
	return nil
}

var File_NotifyServerMsg_proto protoreflect.FileDescriptor

var file_NotifyServerMsg_proto_rawDesc = []byte{
	0x0a, 0x15, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x4d, 0x73,
	0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x6e, 0x65, 0x74, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x1a, 0x0f, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x4d, 0x73, 0x67, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0x87, 0x01, 0x0a, 0x13, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x53, 0x65, 0x72,
	0x76, 0x65, 0x72, 0x52, 0x65, 0x67, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x1a, 0x0a, 0x08, 0x53, 0x65,
	0x72, 0x76, 0x65, 0x72, 0x49, 0x44, 0x18, 0x01, 0x20, 0x02, 0x28, 0x05, 0x52, 0x08, 0x53, 0x65,
	0x72, 0x76, 0x65, 0x72, 0x49, 0x44, 0x12, 0x16, 0x0a, 0x06, 0x47, 0x61, 0x6d, 0x65, 0x49, 0x44,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x47, 0x61, 0x6d, 0x65, 0x49, 0x44, 0x12, 0x1e,
	0x0a, 0x0a, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x54, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x02,
	0x28, 0x05, 0x52, 0x0a, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1c,
	0x0a, 0x09, 0x4c, 0x69, 0x61, 0x6e, 0x79, 0x75, 0x6e, 0x49, 0x44, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x09, 0x4c, 0x69, 0x61, 0x6e, 0x79, 0x75, 0x6e, 0x49, 0x44, 0x22, 0xfc, 0x01, 0x0a,
	0x07, 0x41, 0x6e, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01,
	0x20, 0x02, 0x28, 0x05, 0x52, 0x02, 0x49, 0x44, 0x12, 0x1e, 0x0a, 0x0a, 0x50, 0x6c, 0x61, 0x74,
	0x66, 0x6f, 0x72, 0x6d, 0x49, 0x44, 0x18, 0x02, 0x20, 0x02, 0x28, 0x05, 0x52, 0x0a, 0x50, 0x6c,
	0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x49, 0x44, 0x12, 0x1e, 0x0a, 0x0a, 0x4d, 0x73, 0x67, 0x43,
	0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x02, 0x28, 0x09, 0x52, 0x0a, 0x4d, 0x73,
	0x67, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x54, 0x79, 0x70, 0x65,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x54, 0x79, 0x70, 0x65, 0x12, 0x16, 0x0a, 0x06,
	0x43, 0x6f, 0x64, 0x65, 0x4c, 0x47, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x43, 0x6f,
	0x64, 0x65, 0x4c, 0x47, 0x12, 0x18, 0x0a, 0x07, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x4c, 0x47, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x4c, 0x47, 0x12, 0x28,
	0x0a, 0x05, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x18, 0x07, 0x20, 0x02, 0x28, 0x0e, 0x32, 0x12, 0x2e,
	0x6e, 0x65, 0x74, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x41, 0x6e, 0x6e, 0x52, 0x61, 0x6e, 0x67,
	0x65, 0x52, 0x05, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x12, 0x31, 0x0a, 0x08, 0x50, 0x72, 0x69, 0x6f,
	0x72, 0x69, 0x74, 0x79, 0x18, 0x08, 0x20, 0x02, 0x28, 0x0e, 0x32, 0x15, 0x2e, 0x6e, 0x65, 0x74,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x41, 0x6e, 0x6e, 0x50, 0x72, 0x69, 0x6f, 0x72, 0x69, 0x74,
	0x79, 0x52, 0x08, 0x50, 0x72, 0x69, 0x6f, 0x72, 0x69, 0x74, 0x79, 0x22, 0x2e, 0x0a, 0x07, 0x41,
	0x6e, 0x6e, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x23, 0x0a, 0x03, 0x41, 0x6e, 0x6e, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x6e, 0x65, 0x74, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x41,
	0x6e, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x03, 0x41, 0x6e, 0x6e, 0x22, 0x6a, 0x0a, 0x0a, 0x41,
	0x74, 0x74, 0x72, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x55, 0x73, 0x65,
	0x72, 0x49, 0x44, 0x18, 0x01, 0x20, 0x02, 0x28, 0x05, 0x52, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49,
	0x44, 0x12, 0x16, 0x0a, 0x06, 0x54, 0x79, 0x70, 0x65, 0x49, 0x44, 0x18, 0x02, 0x20, 0x02, 0x28,
	0x05, 0x52, 0x06, 0x54, 0x79, 0x70, 0x65, 0x49, 0x44, 0x12, 0x14, 0x0a, 0x05, 0x50, 0x61, 0x72,
	0x61, 0x6d, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x12,
	0x16, 0x0a, 0x06, 0x53, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x53, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x22, 0x3c, 0x0a, 0x0e, 0x41, 0x74, 0x74, 0x72, 0x43,
	0x68, 0x61, 0x6e, 0x67, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x2a, 0x0a, 0x05, 0x41, 0x74, 0x74,
	0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x6e, 0x65, 0x74, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x41, 0x74, 0x74, 0x72, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x52, 0x05,
	0x41, 0x74, 0x74, 0x72, 0x73, 0x22, 0xa4, 0x01, 0x0a, 0x0a, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72,
	0x53, 0x74, 0x6f, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x54, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x02,
	0x28, 0x05, 0x52, 0x04, 0x54, 0x79, 0x70, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x18, 0x02, 0x20, 0x02, 0x28, 0x05, 0x52, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x12, 0x16, 0x0a, 0x06, 0x47, 0x61, 0x6d, 0x65, 0x49, 0x44, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x06, 0x47, 0x61, 0x6d, 0x65, 0x49, 0x44, 0x12, 0x1a, 0x0a, 0x08, 0x53, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x49, 0x44, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x53, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x49, 0x44, 0x12, 0x18, 0x0a, 0x07, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18,
	0x05, 0x20, 0x02, 0x28, 0x09, 0x52, 0x07, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x1c,
	0x0a, 0x09, 0x4c, 0x69, 0x61, 0x6e, 0x79, 0x75, 0x6e, 0x49, 0x44, 0x18, 0x06, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x09, 0x4c, 0x69, 0x61, 0x6e, 0x79, 0x75, 0x6e, 0x49, 0x44, 0x22, 0x27, 0x0a, 0x15,
	0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x53, 0x74, 0x6f, 0x70, 0x57, 0x68, 0x69, 0x74, 0x65, 0x49,
	0x50, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x50, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x09, 0x52, 0x02, 0x49, 0x50, 0x22, 0x8c, 0x01, 0x0a, 0x08, 0x53, 0x4d, 0x53, 0x56, 0x43, 0x6f,
	0x64, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x43, 0x6f, 0x64, 0x65, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x06, 0x43, 0x6f, 0x64, 0x65, 0x49, 0x44, 0x12, 0x10, 0x0a, 0x03, 0x54, 0x65,
	0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x54, 0x65, 0x6c, 0x12, 0x14, 0x0a, 0x05,
	0x56, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x56, 0x43, 0x6f,
	0x64, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x50, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x49, 0x44,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x50, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d,
	0x49, 0x44, 0x12, 0x20, 0x0a, 0x0b, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79, 0x43, 0x6f, 0x64,
	0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79,
	0x43, 0x6f, 0x64, 0x65, 0x22, 0x38, 0x0a, 0x0c, 0x53, 0x4d, 0x53, 0x56, 0x43, 0x6f, 0x64, 0x65,
	0x4c, 0x69, 0x73, 0x74, 0x12, 0x28, 0x0a, 0x05, 0x41, 0x74, 0x74, 0x72, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x6e, 0x65, 0x74, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53,
	0x4d, 0x53, 0x56, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x05, 0x41, 0x74, 0x74, 0x72, 0x73, 0x22, 0x88,
	0x01, 0x0a, 0x10, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x47, 0x61, 0x6d, 0x65, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x49, 0x44, 0x18,
	0x01, 0x20, 0x02, 0x28, 0x05, 0x52, 0x08, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x49, 0x44, 0x12,
	0x16, 0x0a, 0x06, 0x47, 0x61, 0x6d, 0x65, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x06, 0x47, 0x61, 0x6d, 0x65, 0x49, 0x44, 0x12, 0x22, 0x0a, 0x0c, 0x53, 0x65, 0x72, 0x76, 0x65,
	0x72, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0c, 0x53,
	0x65, 0x72, 0x76, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x1c, 0x0a, 0x09, 0x4c,
	0x69, 0x61, 0x6e, 0x79, 0x75, 0x6e, 0x49, 0x44, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09,
	0x4c, 0x69, 0x61, 0x6e, 0x79, 0x75, 0x6e, 0x49, 0x44, 0x22, 0x59, 0x0a, 0x13, 0x47, 0x61, 0x6d,
	0x65, 0x4c, 0x6f, 0x63, 0x6b, 0x54, 0x72, 0x61, 0x63, 0x65, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65,
	0x12, 0x20, 0x0a, 0x0b, 0x53, 0x75, 0x70, 0x65, 0x72, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x18,
	0x01, 0x20, 0x02, 0x28, 0x05, 0x52, 0x0b, 0x53, 0x75, 0x70, 0x65, 0x72, 0x55, 0x73, 0x65, 0x72,
	0x49, 0x44, 0x12, 0x20, 0x0a, 0x0b, 0x54, 0x72, 0x61, 0x63, 0x65, 0x55, 0x73, 0x65, 0x72, 0x49,
	0x44, 0x18, 0x02, 0x20, 0x02, 0x28, 0x05, 0x52, 0x0b, 0x54, 0x72, 0x61, 0x63, 0x65, 0x55, 0x73,
	0x65, 0x72, 0x49, 0x44, 0x22, 0x5a, 0x0a, 0x17, 0x47, 0x61, 0x6d, 0x65, 0x4c, 0x6f, 0x63, 0x6b,
	0x54, 0x72, 0x61, 0x63, 0x65, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x12,
	0x3f, 0x0a, 0x0b, 0x54, 0x72, 0x61, 0x63, 0x65, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x6e, 0x65, 0x74, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x47, 0x61, 0x6d, 0x65, 0x4c, 0x6f, 0x63, 0x6b, 0x54, 0x72, 0x61, 0x63, 0x65, 0x43, 0x68, 0x61,
	0x6e, 0x67, 0x65, 0x52, 0x0b, 0x54, 0x72, 0x61, 0x63, 0x65, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65,
	0x22, 0xdb, 0x01, 0x0a, 0x0b, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x6e, 0x66, 0x6f,
	0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x02, 0x28, 0x05, 0x52, 0x02, 0x49, 0x44,
	0x12, 0x18, 0x0a, 0x07, 0x42, 0x75, 0x6e, 0x6c, 0x64, 0x49, 0x44, 0x18, 0x02, 0x20, 0x02, 0x28,
	0x09, 0x52, 0x07, 0x42, 0x75, 0x6e, 0x6c, 0x64, 0x49, 0x44, 0x12, 0x10, 0x0a, 0x03, 0x56, 0x65,
	0x72, 0x18, 0x03, 0x20, 0x02, 0x28, 0x09, 0x52, 0x03, 0x56, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x04,
	0x50, 0x61, 0x74, 0x68, 0x18, 0x04, 0x20, 0x02, 0x28, 0x09, 0x52, 0x04, 0x50, 0x61, 0x74, 0x68,
	0x12, 0x12, 0x0a, 0x04, 0x56, 0x65, 0x72, 0x31, 0x18, 0x05, 0x20, 0x02, 0x28, 0x09, 0x52, 0x04,
	0x56, 0x65, 0x72, 0x31, 0x12, 0x1a, 0x0a, 0x08, 0x50, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x50, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d,
	0x12, 0x18, 0x0a, 0x07, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x18, 0x07, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x12, 0x18, 0x0a, 0x07, 0x53, 0x6b,
	0x69, 0x6e, 0x56, 0x65, 0x72, 0x18, 0x08, 0x20, 0x02, 0x28, 0x09, 0x52, 0x07, 0x53, 0x6b, 0x69,
	0x6e, 0x56, 0x65, 0x72, 0x12, 0x18, 0x0a, 0x07, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x49, 0x50, 0x18,
	0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x49, 0x50, 0x22, 0x36,
	0x0a, 0x0b, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x27, 0x0a,
	0x03, 0x56, 0x65, 0x72, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x6e, 0x65, 0x74,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x6e, 0x66,
	0x6f, 0x52, 0x03, 0x56, 0x65, 0x72, 0x42, 0x0c, 0x5a, 0x0a, 0x2e, 0x2f, 0x6e, 0x65, 0x74, 0x70,
	0x72, 0x6f, 0x74, 0x6f,
}

var (
	file_NotifyServerMsg_proto_rawDescOnce sync.Once
	file_NotifyServerMsg_proto_rawDescData = file_NotifyServerMsg_proto_rawDesc
)

func file_NotifyServerMsg_proto_rawDescGZIP() []byte {
	file_NotifyServerMsg_proto_rawDescOnce.Do(func() {
		file_NotifyServerMsg_proto_rawDescData = protoimpl.X.CompressGZIP(file_NotifyServerMsg_proto_rawDescData)
	})
	return file_NotifyServerMsg_proto_rawDescData
}

var file_NotifyServerMsg_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_NotifyServerMsg_proto_goTypes = []interface{}{
	(*NotifyServerRegInfo)(nil),     // 0: netproto.NotifyServerRegInfo
	(*AnnInfo)(nil),                 // 1: netproto.AnnInfo
	(*AnnList)(nil),                 // 2: netproto.AnnList
	(*AttrChange)(nil),              // 3: netproto.AttrChange
	(*AttrChangeList)(nil),          // 4: netproto.AttrChangeList
	(*ServerStop)(nil),              // 5: netproto.ServerStop
	(*ServerStopWhiteIPList)(nil),   // 6: netproto.ServerStopWhiteIPList
	(*SMSVCode)(nil),                // 7: netproto.SMSVCode
	(*SMSVCodeList)(nil),            // 8: netproto.SMSVCodeList
	(*NotifyGameStatus)(nil),        // 9: netproto.NotifyGameStatus
	(*GameLockTraceChange)(nil),     // 10: netproto.GameLockTraceChange
	(*GameLockTraceChangeList)(nil), // 11: netproto.GameLockTraceChangeList
	(*VersionInfo)(nil),             // 12: netproto.VersionInfo
	(*VersionList)(nil),             // 13: netproto.VersionList
	(AnnRange)(0),                   // 14: netproto.AnnRange
	(AnnPriority)(0),                // 15: netproto.AnnPriority
}
var file_NotifyServerMsg_proto_depIdxs = []int32{
	14, // 0: netproto.AnnInfo.Range:type_name -> netproto.AnnRange
	15, // 1: netproto.AnnInfo.Priority:type_name -> netproto.AnnPriority
	1,  // 2: netproto.AnnList.Ann:type_name -> netproto.AnnInfo
	3,  // 3: netproto.AttrChangeList.Attrs:type_name -> netproto.AttrChange
	7,  // 4: netproto.SMSVCodeList.Attrs:type_name -> netproto.SMSVCode
	10, // 5: netproto.GameLockTraceChangeList.TraceChange:type_name -> netproto.GameLockTraceChange
	12, // 6: netproto.VersionList.Ver:type_name -> netproto.VersionInfo
	7,  // [7:7] is the sub-list for method output_type
	7,  // [7:7] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_NotifyServerMsg_proto_init() }
func file_NotifyServerMsg_proto_init() {
	if File_NotifyServerMsg_proto != nil {
		return
	}
	file_CommonMsg_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_NotifyServerMsg_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NotifyServerRegInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_NotifyServerMsg_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AnnInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_NotifyServerMsg_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AnnList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_NotifyServerMsg_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AttrChange); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_NotifyServerMsg_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AttrChangeList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_NotifyServerMsg_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServerStop); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_NotifyServerMsg_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServerStopWhiteIPList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_NotifyServerMsg_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SMSVCode); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_NotifyServerMsg_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SMSVCodeList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_NotifyServerMsg_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NotifyGameStatus); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_NotifyServerMsg_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GameLockTraceChange); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_NotifyServerMsg_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GameLockTraceChangeList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_NotifyServerMsg_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VersionInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_NotifyServerMsg_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VersionList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_NotifyServerMsg_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_NotifyServerMsg_proto_goTypes,
		DependencyIndexes: file_NotifyServerMsg_proto_depIdxs,
		MessageInfos:      file_NotifyServerMsg_proto_msgTypes,
	}.Build()
	File_NotifyServerMsg_proto = out.File
	file_NotifyServerMsg_proto_rawDesc = nil
	file_NotifyServerMsg_proto_goTypes = nil
	file_NotifyServerMsg_proto_depIdxs = nil
}
